export const QUERY_KEYS = {
    allTripsOfHost: 'allTripsOfHost',
    bookingDetails: 'bookingDetails',
    allMasterHostCheckList: 'allMasterHostCheckList',
    allChannels: 'allChannels',
    chatHistory: 'chatHistory',
    allDriversOfHost: 'allDriversOfHost',
    driverRentalHistory: 'driverRentalHistory',
    driverLicenseDetails: 'driverLicenseDetails',
    hostConstraints: 'hostConstraints',
    allHosts: 'allHosts',
    allEmployees: 'allEmployees',
    allNotifications: 'allNotifications',
    telematicsDataByVehicleId: 'telematicsDataByVehicleId',
    telematicsEventsOfTripById: 'telematicsEventsOfTripById',
    allVechiclesUnderHost: 'allVechiclesUnderHost',
    vehiclesByVin: 'vehiclesByVin',
    vehicleFeaturesById: 'vehicleFeaturesById',
    vehicleUpdateLogsById: 'vehicleUpdateLogsById',
    vehicleTripById: 'vehicleTripById'
};
