export const QUERY_KEYS = {
    allTripsOfHost: 'allTripsOfHost',
    allDailyViewTrips: 'allDailyViewTrips',
    allReviewRequiredTrips: 'allReviewRequiredTrips',
    tripDetails: 'tripDetails',
    allMasterHostCheckList: 'allMasterHostCheckList',
    allChannels: 'allChannels',
    chatHistory: 'chatHistory',
    allDriversOfHost: 'allDriversOfHost',
    guestsRentalHistory: 'guestsRentalHistory',
    driverLicenseDetails: 'driverLicenseDetails',
    hostConstraints: 'hostConstraints',
    allHosts: 'allHosts',
    allEmployees: 'allEmployees',
    allNotifications: 'allNotifications',
    telematicsDataByVehicleId: 'telematicsDataByVehicleId',
    telematicsEventsOfTripById: 'telematicsEventsOfTripById',
    allVechiclesUnderHost: 'allVechiclesUnderHost',
    vehiclesForMapView: 'vehiclesForMapView',
    vehiclesByVin: 'vehiclesByVin',
    vehicleFeaturesById: 'vehicleFeaturesById',
    vehicleUpdateLogsById: 'vehicleUpdateLogsById',
    vehicleTripById: 'vehicleTripById',
    vehicleConfigurationEvents: 'vehicleConfigurationEvents',
    vehicleRepairLogs: 'vehicleRepairLogs',
    vehicleExpenseLogs: 'vehicleExpenseLogs'
};
