export const activeTrip = {
    hostVehicleTrips: [],
    driverHostConfigs: [],
    paymentIntent: null,
    driverReadinesses: [],
    depositHoldRespons: [],
    notificationEvents: [],
    tripConstraints: [],
    checkLists: [
        {
            id: 30,
            tripId: 2259,
            startFuelLevel: 'Full',
            endFuelLevel: 'Full',
            ac: true,
            wiperFluid: true,
            oil: false,
            preTripCarCleaned: false,
            postTripCarCleaned: true,
            brakes: true,
            headLight: false,
            preTripComments: 'testing 123',
            postTripComments: ''
        }
    ],
    paymentLogs: [],
    insuranceDetails: [],
    processedPayments: {
        '2025-01-01 17:35:54+00': 73.2852478,
        '2025-01-01 18:16:07+00': 7.57749986,
        '2025-01-01 13:33:12+00': 5.4124999
    },
    failedPaymentLogs: {},
    chargesList: null,
    pendingPayments: {},
    refundedAmount: 0.0,
    pendingDeductions: null,
    pendingRecords: {},
    hostBusinessConstraints: [],
    telematicsMessageLogs: [],
    turoMailRecords: [],
    hostPriceResponses: [],
    failedReservations: [],
    deliveryLocations: [],
    stripePayments: [],
    inAppNotifications: [],
    vehicleUnavaliblityDetails: [],
    vehicleLogResponses: [],
    reservationResponse: [],
    reserverList: [],
    userResponse: null,
    swapLogs: [],
    swapDetails: [],
    errorResponses: [],
    swapDetailResponses: [],
    vehicleHostDetails: null,
    paymentresponse: [],
    activetripresponse: [
        {
            cardDetails: [
                {
                    id: 159,
                    userId: 1429,
                    tripId: 2259,
                    oldMethodIdToken: '',
                    newMethodIdToken: 'pm_1QcS2oAHBUVqiOLMoPyQHwgW',
                    createdDate: '2025-01-01 13:33:10.71759+00',
                    updatedDate: null,
                    isActive: true,
                    cardType: 'credit',
                    last4Digit: '4444',
                    cardBrand: 'mastercard'
                }
            ],
            deliveryLocations: null,
            isDebitCard: false,
            version: 3,
            tripModificationHistories: [],
            swapDetails: [],
            insuranceDetails: [
                {
                    id: 2,
                    userId: 1429,
                    itemId: null,
                    requestId: null,
                    individualId: 'idv_2nBsKvwGsfFBeMRJla3IyO4mXAg',
                    isExpired: false,
                    isActive: true,
                    isVerified: false,
                    expiryDate: null,
                    verifiedStatus: null,
                    policyNumber: null,
                    insuranceProvider: null,
                    policyHolders: null,
                    coverages: null,
                    startDate: null,
                    createdTime: '2024-10-17 09:09:52.132886+00',
                    updatedTime: '2024-12-29 15:50:20.774+00'
                }
            ],
            driverProfiles: [
                {
                    id: 40,
                    userId: 1429,
                    fromValue: null,
                    idScanRequestID: '2e6411f0-67e9-4262-834b-441c7cd20dc6',
                    isActive: true,
                    isExpired: false,
                    isVerified: true,
                    createdTime: '2024-12-13 14:52:54.546941+00',
                    updatedTime: '2024-12-16 05:03:55.384+00',
                    expiryDate: '2032-07-07 00:00:00+00',
                    drivingLicenseStatus: 'verified'
                }
            ],
            vehicleImages: [
                {
                    idimage: 114,
                    orderNumber: 1,
                    isPrimary: true,
                    vehicleid: 34,
                    imagename: 'https://fiat.b-cdn.net/H4185736.jpeg',
                    userid: 1,
                    isactive: true,
                    createdate: '2023-11-07 14:22:52.995225+00',
                    updatedate: '2023-11-07 14:22:52.995225+00',
                    imageUuid: null
                }
            ],
            tripPaymentTokens: [
                {
                    capturedDays: 0,
                    depositHoldAmount: 0.0,
                    chargedAmountOnHold: 0.0,
                    id: 2352,
                    reservationid: 2260,
                    userid: 1429,
                    hostid: 1418,
                    channelid: 1,
                    vehicleid: 34,
                    deductionfrequencyconfigid: 1,
                    paymentauthorizationconfigid: 0,
                    authorizationamount: 15.7395496,
                    authorizationpercentage: 20.0,
                    releasedAmountOnHold: 0.0,
                    totaldays: 2.0,
                    perdayamount: 30.0,
                    totalamount: 94.0,
                    createddate: '2025-01-01 13:33:10.71338+00',
                    updateddate: null,
                    tripid: 2259,
                    strippaymenttoken: 'NA',
                    strippaymentid: 'NA',
                    strippaymenttokenactiveflag: false,
                    isactive: true,
                    paymentrecieveddate: '2025-01-01 13:33:10.71338+00',
                    stripetransactiondetails: '{"key1": "val1"}',
                    paymentmethodidtoken: 'pm_1QcS2oAHBUVqiOLMoPyQHwgW',
                    customertoken: 'cus_Qv7Gln3W3dqssN',
                    setupIntentToken: 'NA',
                    tripAmount: 79.6999969,
                    taxAmount: 6.57524967,
                    tripTaxAmount: 86.2752457,
                    discountedDays: 2.0,
                    discountPercentage: 0.0,
                    discountAmount: 0.0,
                    tripDiscountedAmount: 60.0,
                    upCharges: 0.0,
                    deliveryCost: 0.0,
                    tripFee: 5.0,
                    charges: 60.0,
                    taxPercentage: 8.25,
                    numberOfDaysDiscount: 0.0,
                    concessionCalculated: 0.0,
                    concessionPercentage: 0.0,
                    concessionFee: 0.0,
                    registrationRecoveryFee: 0.5,
                    extreaMilageCost: 0.0,
                    Statesurchargetax: 12.0,
                    Statesurchargeamount: 7.19999981,
                    tripFeeAmount: 12.6999998,
                    capturedAmount: 86.2799988,
                    refundAmount: 0.0,
                    extraMileageCost: 0.0,
                    extraMilage: 0.0,
                    lateFee: 5.0,
                    extraDayCharges: 2.0,
                    registrationFee: 30.0,
                    averageRentalDays: 120.0
                }
            ],
            paymentTransactions: [
                {
                    id: 6881,
                    userid: 1429,
                    vehicleid: 34,
                    reservationid: 2259,
                    tripid: 2259,
                    hostid: 1418,
                    trippaymenttokenid: 0,
                    channelid: 1,
                    stripetoken: 'pi_3QcS2tAHBUVqiOLM2Yh3oVTQ',
                    stripetokenid: 'cus_Qv7Gln3W3dqssN',
                    amount: 541.0,
                    stripestatus: 'succeeded',
                    paymentinitiated: '2025-01-01 13:33:12.248285+00',
                    paymentdate: '2025-01-01 13:33:12.248285+00',
                    createddate: '2025-01-01 13:33:12.248285+00',
                    updateddate: '2025-01-01 13:33:12.248285+00',
                    stripeResponse:
                        '<com.stripe.model.PaymentIntent@867368522 id=pi_3QcS2tAHBUVqiOLM2Yh3oVTQ> JSON: {\n  "amount": 541,\n  "amount_capturable": 0,\n  "amount_details": {\n    "tip": {\n      "amount": null\n    }\n  },\n  "amount_received": 541,\n  "application": null,\n  "application_fee_amount": null,\n  "automatic_payment_methods": null,\n  "canceled_at": null,\n  "cancellation_reason": null,\n  "capture_method": "automatic",\n  "charges": {\n    "object": "list",\n    "data": [\n      {\n        "alternate_statement_descriptors": null,\n        "amount": 541,\n        "amount_captured": 541,\n        "amount_refunded": 0,\n        "application": null,\n        "application_fee": null,\n        "application_fee_amount": null,\n        "authorization_code": null,\n        "balance_transaction": "txn_3QcS2tAHBUVqiOLM2YFL8ZO5",\n        "billing_details": {\n          "address": {\n            "city": null,\n            "country": "IN",\n            "line1": null,\n            "line2": null,\n            "postal_code": null,\n            "state": null\n          },\n          "email": null,\n          "name": null,\n          "phone": null\n        },\n        "calculated_statement_descriptor": "WWW.MYBUNDEE.COM",\n        "captured": true,\n        "created": 1735738391,\n        "currency": "usd",\n        "customer": "cus_Qv7Gln3W3dqssN",\n        "description": null,\n        "destination": null,\n        "dispute": null,\n        "disputed": false,\n        "failure_balance_transaction": null,\n        "failure_code": null,\n        "failure_message": null,\n        "fraud_details": {\n          "stripe_report": null,\n          "user_report": null\n        },\n        "id": "ch_3QcS2tAHBUVqiOLM2EHImRY4",\n        "invoice": null,\n        "level3": null,\n        "livemode": false,\n        "metadata": {},\n        "object": "charge",\n        "on_behalf_of": null,\n        "order": null,\n        "outcome": {\n          "network_status": "approved_by_network",\n          "reason": null,\n          "risk_level": "normal",\n          "risk_score": 56,\n          "rule": null,\n          "seller_message": "Payment complete.",\n          "type": "authorized"\n        },\n        "paid": true,\n        "payment_intent": "pi_3QcS2tAHBUVqiOLM2Yh3oVTQ",\n        "payment_method": "pm_1QcS2oAHBUVqiOLMoPyQHwgW",\n        "payment_method_details": {\n          "ach_credit_transfer": null,\n          "ach_debit": null,\n          "acss_debit": null,\n          "afterpay_clearpay": null,\n          "alipay": null,\n          "au_becs_debit": null,\n          "bacs_debit": null,\n          "bancontact": null,\n          "boleto": null,\n          "card": {\n            "brand": "mastercard",\n            "checks": {\n              "address_line1_check": null,\n              "address_postal_code_check": null,\n              "cvc_check": "pass"\n            },\n            "country": "US",\n            "description": null,\n            "exp_month": 4,\n            "exp_year": 2035,\n            "fingerprint": "yGiK8L37nQ0YI2ub",\n            "funding": "credit",\n            "iin": null,\n            "installments": null,\n            "issuer": null,\n            "last4": "4444",\n            "mandate": null,\n            "moto": null,\n            "network": "mastercard",\n            "three_d_secure": null,\n            "wallet": null\n          },\n          "card_present": null,\n          "customer_balance": null,\n          "eps": null,\n          "fpx": null,\n          "giropay": null,\n          "grabpay": null,\n          "ideal": null,\n          "interac_present": null,\n          "klarna": null,\n          "konbini": null,\n          "multibanco": null,\n          "oxxo": null,\n          "p24": null,\n          "paynow": null,\n          "sepa_credit_transfer": null,\n          "sepa_debit": null,\n          "sofort": null,\n          "stripe_account": null,\n          "type": "card",\n          "us_bank_account": null,\n          "wechat": null,\n          "wechat_pay": null\n        },\n        "receipt_email": null,\n        "receipt_number": null,\n        "receipt_url": "https://pay.stripe.com/receipts/payment/CAcaFwoVYWNjdF8xTmljN1dBSEJVVnFpT0xNKJiI1bsGMgZlNilY5Po6LBbZENVYnC8vrjuLldiNIWcrPv2Y6Za1ZAPo0DBcrlSbxzC9aSJHnqgaEFwV",\n        "refunded": false,\n        "refunds": {\n          "object": "list",\n          "data": [],\n          "has_more": false,\n          "url": "/v1/charges/ch_3QcS2tAHBUVqiOLM2EHImRY4/refunds",\n          "request_params": null\n        },\n        "review": null,\n        "shipping": null,\n        "source": null,\n        "source_transfer": null,\n        "statement_descriptor": null,\n        "statement_descriptor_suffix": null,\n        "status": "succeeded",\n        "transfer": null,\n        "transfer_data": null,\n        "transfer_group": null\n      }\n    ],\n    "has_more": false,\n    "url": "/v1/charges?payment_intent=pi_3QcS2tAHBUVqiOLM2Yh3oVTQ",\n    "request_params": null\n  },\n  "client_secret": "pi_3QcS2tAHBUVqiOLM2Yh3oVTQ_secret_G4v2Hyu9B4YeRhJ3EdNc6nyTM",\n  "confirmation_method": "automatic",\n  "created": 1735738391,\n  "currency": "usd",\n  "customer": "cus_Qv7Gln3W3dqssN",\n  "description": null,\n  "id": "pi_3QcS2tAHBUVqiOLM2Yh3oVTQ",\n  "invoice": null,\n  "last_payment_error": null,\n  "livemode": false,\n  "metadata": {},\n  "next_action": null,\n  "object": "payment_intent",\n  "on_behalf_of": null,\n  "payment_method": "pm_1QcS2oAHBUVqiOLMoPyQHwgW",\n  "payment_method_options": {\n    "acss_debit": null,\n    "afterpay_clearpay": null,\n    "alipay": null,\n    "au_becs_debit": null,\n    "bacs_debit": null,\n    "bancontact": null,\n    "boleto": null,\n    "card": {\n      "capture_method": null,\n      "installments": null,\n      "mandate_options": null,\n      "network": null,\n      "request_three_d_secure": "automatic",\n      "setup_future_usage": null\n    },\n    "card_present": null,\n    "customer_balance": null,\n    "eps": null,\n    "fpx": null,\n    "giropay": null,\n    "grabpay": null,\n    "ideal": null,\n    "interac_present": null,\n    "klarna": null,\n    "konbini": null,\n    "oxxo": null,\n    "p24": null,\n    "paynow": null,\n    "sepa_debit": null,\n    "sofort": null,\n    "us_bank_account": null,\n    "wechat_pay": null\n  },\n  "payment_method_types": [\n    "card"\n  ],\n  "processing": null,\n  "receipt_email": null,\n  "review": null,\n  "setup_future_usage": null,\n  "shipping": null,\n  "source": null,\n  "statement_descriptor": null,\n  "statement_descriptor_suffix": null,\n  "status": "succeeded",\n  "transfer_data": null,\n  "transfer_group": null\n}',
                    channelName: null,
                    referenceId: 'ch_3QcS2tAHBUVqiOLM2EHImRY4',
                    collected: true
                },
                {
                    id: 6882,
                    userid: 1429,
                    vehicleid: 34,
                    reservationid: 2260,
                    tripid: 2259,
                    hostid: 1418,
                    trippaymenttokenid: 2352,
                    channelid: 1,
                    stripetoken: 'pi_3QcS2tAHBUVqiOLM2Yh3oVTQ',
                    stripetokenid: 'cus_Qv7Gln3W3dqssN',
                    amount: 541.0,
                    stripestatus: 'succeeded',
                    paymentinitiated: '2025-01-01 13:33:12.256787+00',
                    paymentdate: '2025-01-01 13:33:12.256787+00',
                    createddate: '2025-01-01 13:33:12.256787+00',
                    updateddate: '2025-01-01 13:33:12.256787+00',
                    stripeResponse: null,
                    channelName: null,
                    referenceId: null,
                    collected: false
                },
                {
                    id: 6903,
                    userid: 1429,
                    vehicleid: 34,
                    reservationid: 2259,
                    tripid: 2259,
                    hostid: 1418,
                    trippaymenttokenid: 0,
                    channelid: 1,
                    stripetoken: 'pi_3QcVplAHBUVqiOLM2sLoDD2l',
                    stripetokenid: 'cus_Qv7Gln3W3dqssN',
                    amount: 7329.0,
                    stripestatus: 'succeeded',
                    paymentinitiated: '2025-01-01 17:35:54.765523+00',
                    paymentdate: '2025-01-01 17:35:54.765523+00',
                    createddate: '2025-01-01 17:35:54.765523+00',
                    updateddate: '2025-01-01 17:35:54.765523+00',
                    stripeResponse:
                        '<com.stripe.model.PaymentIntent@1109842402 id=pi_3QcVplAHBUVqiOLM2sLoDD2l> JSON: {\n  "amount": 7329,\n  "amount_capturable": 0,\n  "amount_details": {\n    "tip": {\n      "amount": null\n    }\n  },\n  "amount_received": 7329,\n  "application": null,\n  "application_fee_amount": null,\n  "automatic_payment_methods": null,\n  "canceled_at": null,\n  "cancellation_reason": null,\n  "capture_method": "automatic",\n  "charges": {\n    "object": "list",\n    "data": [\n      {\n        "alternate_statement_descriptors": null,\n        "amount": 7329,\n        "amount_captured": 7329,\n        "amount_refunded": 0,\n        "application": null,\n        "application_fee": null,\n        "application_fee_amount": null,\n        "authorization_code": null,\n        "balance_transaction": "txn_3QcVplAHBUVqiOLM2GHj5n2w",\n        "billing_details": {\n          "address": {\n            "city": null,\n            "country": "IN",\n            "line1": null,\n            "line2": null,\n            "postal_code": null,\n            "state": null\n          },\n          "email": null,\n          "name": null,\n          "phone": null\n        },\n        "calculated_statement_descriptor": "WWW.MYBUNDEE.COM",\n        "captured": true,\n        "created": 1735752954,\n        "currency": "usd",\n        "customer": "cus_Qv7Gln3W3dqssN",\n        "description": null,\n        "destination": null,\n        "dispute": null,\n        "disputed": false,\n        "failure_balance_transaction": null,\n        "failure_code": null,\n        "failure_message": null,\n        "fraud_details": {\n          "stripe_report": null,\n          "user_report": null\n        },\n        "id": "ch_3QcVplAHBUVqiOLM2UyQ4S6n",\n        "invoice": null,\n        "level3": null,\n        "livemode": false,\n        "metadata": {},\n        "object": "charge",\n        "on_behalf_of": null,\n        "order": null,\n        "outcome": {\n          "network_status": "approved_by_network",\n          "reason": null,\n          "risk_level": "normal",\n          "risk_score": 17,\n          "rule": null,\n          "seller_message": "Payment complete.",\n          "type": "authorized"\n        },\n        "paid": true,\n        "payment_intent": "pi_3QcVplAHBUVqiOLM2sLoDD2l",\n        "payment_method": "pm_1QcS2oAHBUVqiOLMoPyQHwgW",\n        "payment_method_details": {\n          "ach_credit_transfer": null,\n          "ach_debit": null,\n          "acss_debit": null,\n          "afterpay_clearpay": null,\n          "alipay": null,\n          "au_becs_debit": null,\n          "bacs_debit": null,\n          "bancontact": null,\n          "boleto": null,\n          "card": {\n            "brand": "mastercard",\n            "checks": {\n              "address_line1_check": null,\n              "address_postal_code_check": null,\n              "cvc_check": null\n            },\n            "country": "US",\n            "description": null,\n            "exp_month": 4,\n            "exp_year": 2035,\n            "fingerprint": "yGiK8L37nQ0YI2ub",\n            "funding": "credit",\n            "iin": null,\n            "installments": null,\n            "issuer": null,\n            "last4": "4444",\n            "mandate": null,\n            "moto": null,\n            "network": "mastercard",\n            "three_d_secure": null,\n            "wallet": null\n          },\n          "card_present": null,\n          "customer_balance": null,\n          "eps": null,\n          "fpx": null,\n          "giropay": null,\n          "grabpay": null,\n          "ideal": null,\n          "interac_present": null,\n          "klarna": null,\n          "konbini": null,\n          "multibanco": null,\n          "oxxo": null,\n          "p24": null,\n          "paynow": null,\n          "sepa_credit_transfer": null,\n          "sepa_debit": null,\n          "sofort": null,\n          "stripe_account": null,\n          "type": "card",\n          "us_bank_account": null,\n          "wechat": null,\n          "wechat_pay": null\n        },\n        "receipt_email": null,\n        "receipt_number": null,\n        "receipt_url": "https://pay.stripe.com/receipts/payment/CAcaFwoVYWNjdF8xTmljN1dBSEJVVnFpT0xNKPr51bsGMgbxQe9hK8w6LBYkqGi6i9bAJzl7tQGj-FWRzmLQzauP2Wlf9rWKE5eHpjDRTpr9U-hTfECs",\n        "refunded": false,\n        "refunds": {\n          "object": "list",\n          "data": [],\n          "has_more": false,\n          "url": "/v1/charges/ch_3QcVplAHBUVqiOLM2UyQ4S6n/refunds",\n          "request_params": null\n        },\n        "review": null,\n        "shipping": null,\n        "source": null,\n        "source_transfer": null,\n        "statement_descriptor": null,\n        "statement_descriptor_suffix": null,\n        "status": "succeeded",\n        "transfer": null,\n        "transfer_data": null,\n        "transfer_group": null\n      }\n    ],\n    "has_more": false,\n    "url": "/v1/charges?payment_intent=pi_3QcVplAHBUVqiOLM2sLoDD2l",\n    "request_params": null\n  },\n  "client_secret": "pi_3QcVplAHBUVqiOLM2sLoDD2l_secret_HkI58csTPK56eewBEuVK0SenK",\n  "confirmation_method": "automatic",\n  "created": 1735752953,\n  "currency": "usd",\n  "customer": "cus_Qv7Gln3W3dqssN",\n  "description": null,\n  "id": "pi_3QcVplAHBUVqiOLM2sLoDD2l",\n  "invoice": null,\n  "last_payment_error": null,\n  "livemode": false,\n  "metadata": {},\n  "next_action": null,\n  "object": "payment_intent",\n  "on_behalf_of": null,\n  "payment_method": "pm_1QcS2oAHBUVqiOLMoPyQHwgW",\n  "payment_method_options": {\n    "acss_debit": null,\n    "afterpay_clearpay": null,\n    "alipay": null,\n    "au_becs_debit": null,\n    "bacs_debit": null,\n    "bancontact": null,\n    "boleto": null,\n    "card": {\n      "capture_method": null,\n      "installments": null,\n      "mandate_options": null,\n      "network": null,\n      "request_three_d_secure": "automatic",\n      "setup_future_usage": null\n    },\n    "card_present": null,\n    "customer_balance": null,\n    "eps": null,\n    "fpx": null,\n    "giropay": null,\n    "grabpay": null,\n    "ideal": null,\n    "interac_present": null,\n    "klarna": null,\n    "konbini": null,\n    "oxxo": null,\n    "p24": null,\n    "paynow": null,\n    "sepa_debit": null,\n    "sofort": null,\n    "us_bank_account": null,\n    "wechat_pay": null\n  },\n  "payment_method_types": [\n    "card"\n  ],\n  "processing": null,\n  "receipt_email": null,\n  "review": null,\n  "setup_future_usage": null,\n  "shipping": null,\n  "source": null,\n  "statement_descriptor": null,\n  "statement_descriptor_suffix": null,\n  "status": "succeeded",\n  "transfer_data": null,\n  "transfer_group": null\n}',
                    channelName: null,
                    referenceId: 'ch_3QcVplAHBUVqiOLM2UyQ4S6n',
                    collected: true
                },
                {
                    id: 6904,
                    userid: 1429,
                    vehicleid: 34,
                    reservationid: 2260,
                    tripid: 2259,
                    hostid: 1418,
                    trippaymenttokenid: 2352,
                    channelid: 1,
                    stripetoken: 'pi_3QcVplAHBUVqiOLM2sLoDD2l',
                    stripetokenid: 'cus_Qv7Gln3W3dqssN',
                    amount: 7329.0,
                    stripestatus: 'succeeded',
                    paymentinitiated: '2025-01-01 17:35:54.774718+00',
                    paymentdate: '2025-01-01 17:35:54.774718+00',
                    createddate: '2025-01-01 17:35:54.774718+00',
                    updateddate: '2025-01-01 17:35:54.774718+00',
                    stripeResponse: null,
                    channelName: null,
                    referenceId: null,
                    collected: false
                },
                {
                    id: 6905,
                    userid: 1429,
                    vehicleid: 34,
                    reservationid: 2259,
                    tripid: 2259,
                    hostid: 1418,
                    trippaymenttokenid: 0,
                    channelid: 1,
                    stripetoken: 'pi_3QcWSgAHBUVqiOLM34UWIlkB',
                    stripetokenid: 'cus_Qv7Gln3W3dqssN',
                    amount: 758.0,
                    stripestatus: 'succeeded',
                    paymentinitiated: '2025-01-01 18:16:07.115887+00',
                    paymentdate: '2025-01-01 18:16:07.115887+00',
                    createddate: '2025-01-01 18:16:07.115887+00',
                    updateddate: '2025-01-01 18:16:07.115887+00',
                    stripeResponse:
                        '<com.stripe.model.PaymentIntent@420612621 id=pi_3QcWSgAHBUVqiOLM34UWIlkB> JSON: {\n  "amount": 758,\n  "amount_capturable": 0,\n  "amount_details": {\n    "tip": {\n      "amount": null\n    }\n  },\n  "amount_received": 758,\n  "application": null,\n  "application_fee_amount": null,\n  "automatic_payment_methods": null,\n  "canceled_at": null,\n  "cancellation_reason": null,\n  "capture_method": "automatic",\n  "charges": {\n    "object": "list",\n    "data": [\n      {\n        "alternate_statement_descriptors": null,\n        "amount": 758,\n        "amount_captured": 758,\n        "amount_refunded": 0,\n        "application": null,\n        "application_fee": null,\n        "application_fee_amount": null,\n        "authorization_code": null,\n        "balance_transaction": "txn_3QcWSgAHBUVqiOLM3lyw3ZVy",\n        "billing_details": {\n          "address": {\n            "city": null,\n            "country": "IN",\n            "line1": null,\n            "line2": null,\n            "postal_code": null,\n            "state": null\n          },\n          "email": null,\n          "name": null,\n          "phone": null\n        },\n        "calculated_statement_descriptor": "WWW.MYBUNDEE.COM",\n        "captured": true,\n        "created": 1735755366,\n        "currency": "usd",\n        "customer": "cus_Qv7Gln3W3dqssN",\n        "description": null,\n        "destination": null,\n        "dispute": null,\n        "disputed": false,\n        "failure_balance_transaction": null,\n        "failure_code": null,\n        "failure_message": null,\n        "fraud_details": {\n          "stripe_report": null,\n          "user_report": null\n        },\n        "id": "ch_3QcWSgAHBUVqiOLM3XJyn3Rg",\n        "invoice": null,\n        "level3": null,\n        "livemode": false,\n        "metadata": {},\n        "object": "charge",\n        "on_behalf_of": null,\n        "order": null,\n        "outcome": {\n          "network_status": "approved_by_network",\n          "reason": null,\n          "risk_level": "normal",\n          "risk_score": 40,\n          "rule": null,\n          "seller_message": "Payment complete.",\n          "type": "authorized"\n        },\n        "paid": true,\n        "payment_intent": "pi_3QcWSgAHBUVqiOLM34UWIlkB",\n        "payment_method": "pm_1QcS2oAHBUVqiOLMoPyQHwgW",\n        "payment_method_details": {\n          "ach_credit_transfer": null,\n          "ach_debit": null,\n          "acss_debit": null,\n          "afterpay_clearpay": null,\n          "alipay": null,\n          "au_becs_debit": null,\n          "bacs_debit": null,\n          "bancontact": null,\n          "boleto": null,\n          "card": {\n            "brand": "mastercard",\n            "checks": {\n              "address_line1_check": null,\n              "address_postal_code_check": null,\n              "cvc_check": null\n            },\n            "country": "US",\n            "description": null,\n            "exp_month": 4,\n            "exp_year": 2035,\n            "fingerprint": "yGiK8L37nQ0YI2ub",\n            "funding": "credit",\n            "iin": null,\n            "installments": null,\n            "issuer": null,\n            "last4": "4444",\n            "mandate": null,\n            "moto": null,\n            "network": "mastercard",\n            "three_d_secure": null,\n            "wallet": null\n          },\n          "card_present": null,\n          "customer_balance": null,\n          "eps": null,\n          "fpx": null,\n          "giropay": null,\n          "grabpay": null,\n          "ideal": null,\n          "interac_present": null,\n          "klarna": null,\n          "konbini": null,\n          "multibanco": null,\n          "oxxo": null,\n          "p24": null,\n          "paynow": null,\n          "sepa_credit_transfer": null,\n          "sepa_debit": null,\n          "sofort": null,\n          "stripe_account": null,\n          "type": "card",\n          "us_bank_account": null,\n          "wechat": null,\n          "wechat_pay": null\n        },\n        "receipt_email": null,\n        "receipt_number": null,\n        "receipt_url": "https://pay.stripe.com/receipts/payment/CAcaFwoVYWNjdF8xTmljN1dBSEJVVnFpT0xNKOaM1rsGMgb8Jb9sv-86LBau3GovZZsRSJ-SgQFnXQUAVMNAovhghi_h1W0Tb5Y07e9of1RFkS_4k8fE",\n        "refunded": false,\n        "refunds": {\n          "object": "list",\n          "data": [],\n          "has_more": false,\n          "url": "/v1/charges/ch_3QcWSgAHBUVqiOLM3XJyn3Rg/refunds",\n          "request_params": null\n        },\n        "review": null,\n        "shipping": null,\n        "source": null,\n        "source_transfer": null,\n        "statement_descriptor": null,\n        "statement_descriptor_suffix": null,\n        "status": "succeeded",\n        "transfer": null,\n        "transfer_data": null,\n        "transfer_group": null\n      }\n    ],\n    "has_more": false,\n    "url": "/v1/charges?payment_intent=pi_3QcWSgAHBUVqiOLM34UWIlkB",\n    "request_params": null\n  },\n  "client_secret": "pi_3QcWSgAHBUVqiOLM34UWIlkB_secret_qfxjtcufuQA6NkY2hi8KGgfbI",\n  "confirmation_method": "automatic",\n  "created": 1735755366,\n  "currency": "usd",\n  "customer": "cus_Qv7Gln3W3dqssN",\n  "description": null,\n  "id": "pi_3QcWSgAHBUVqiOLM34UWIlkB",\n  "invoice": null,\n  "last_payment_error": null,\n  "livemode": false,\n  "metadata": {},\n  "next_action": null,\n  "object": "payment_intent",\n  "on_behalf_of": null,\n  "payment_method": "pm_1QcS2oAHBUVqiOLMoPyQHwgW",\n  "payment_method_options": {\n    "acss_debit": null,\n    "afterpay_clearpay": null,\n    "alipay": null,\n    "au_becs_debit": null,\n    "bacs_debit": null,\n    "bancontact": null,\n    "boleto": null,\n    "card": {\n      "capture_method": null,\n      "installments": null,\n      "mandate_options": null,\n      "network": null,\n      "request_three_d_secure": "automatic",\n      "setup_future_usage": null\n    },\n    "card_present": null,\n    "customer_balance": null,\n    "eps": null,\n    "fpx": null,\n    "giropay": null,\n    "grabpay": null,\n    "ideal": null,\n    "interac_present": null,\n    "klarna": null,\n    "konbini": null,\n    "oxxo": null,\n    "p24": null,\n    "paynow": null,\n    "sepa_debit": null,\n    "sofort": null,\n    "us_bank_account": null,\n    "wechat_pay": null\n  },\n  "payment_method_types": [\n    "card"\n  ],\n  "processing": null,\n  "receipt_email": null,\n  "review": null,\n  "setup_future_usage": null,\n  "shipping": null,\n  "source": null,\n  "statement_descriptor": null,\n  "statement_descriptor_suffix": null,\n  "status": "succeeded",\n  "transfer_data": null,\n  "transfer_group": null\n}',
                    channelName: null,
                    referenceId: 'ch_3QcWSgAHBUVqiOLM3XJyn3Rg',
                    collected: true
                },
                {
                    id: 6906,
                    userid: 1429,
                    vehicleid: 34,
                    reservationid: 2260,
                    tripid: 2259,
                    hostid: 1418,
                    trippaymenttokenid: 2352,
                    channelid: 1,
                    stripetoken: 'pi_3QcWSgAHBUVqiOLM34UWIlkB',
                    stripetokenid: 'cus_Qv7Gln3W3dqssN',
                    amount: 758.0,
                    stripestatus: 'succeeded',
                    paymentinitiated: '2025-01-01 18:16:07.123951+00',
                    paymentdate: '2025-01-01 18:16:07.123951+00',
                    createddate: '2025-01-01 18:16:07.123951+00',
                    updateddate: '2025-01-01 18:16:07.123951+00',
                    stripeResponse: null,
                    channelName: null,
                    referenceId: null,
                    collected: false
                }
            ],
            successfullPaymentTransactions: [
                {
                    id: 6881,
                    userid: 1429,
                    vehicleid: 34,
                    reservationid: 2259,
                    tripid: 2259,
                    hostid: 1418,
                    trippaymenttokenid: 0,
                    channelid: 1,
                    stripetoken: 'pi_3QcS2tAHBUVqiOLM2Yh3oVTQ',
                    stripetokenid: 'cus_Qv7Gln3W3dqssN',
                    amount: 541.0,
                    stripestatus: 'succeeded',
                    paymentinitiated: '2025-01-01 13:33:12.248285+00',
                    paymentdate: '2025-01-01 13:33:12.248285+00',
                    createddate: '2025-01-01 13:33:12.248285+00',
                    updateddate: '2025-01-01 13:33:12.248285+00',
                    stripeResponse:
                        '<com.stripe.model.PaymentIntent@867368522 id=pi_3QcS2tAHBUVqiOLM2Yh3oVTQ> JSON: {\n  "amount": 541,\n  "amount_capturable": 0,\n  "amount_details": {\n    "tip": {\n      "amount": null\n    }\n  },\n  "amount_received": 541,\n  "application": null,\n  "application_fee_amount": null,\n  "automatic_payment_methods": null,\n  "canceled_at": null,\n  "cancellation_reason": null,\n  "capture_method": "automatic",\n  "charges": {\n    "object": "list",\n    "data": [\n      {\n        "alternate_statement_descriptors": null,\n        "amount": 541,\n        "amount_captured": 541,\n        "amount_refunded": 0,\n        "application": null,\n        "application_fee": null,\n        "application_fee_amount": null,\n        "authorization_code": null,\n        "balance_transaction": "txn_3QcS2tAHBUVqiOLM2YFL8ZO5",\n        "billing_details": {\n          "address": {\n            "city": null,\n            "country": "IN",\n            "line1": null,\n            "line2": null,\n            "postal_code": null,\n            "state": null\n          },\n          "email": null,\n          "name": null,\n          "phone": null\n        },\n        "calculated_statement_descriptor": "WWW.MYBUNDEE.COM",\n        "captured": true,\n        "created": 1735738391,\n        "currency": "usd",\n        "customer": "cus_Qv7Gln3W3dqssN",\n        "description": null,\n        "destination": null,\n        "dispute": null,\n        "disputed": false,\n        "failure_balance_transaction": null,\n        "failure_code": null,\n        "failure_message": null,\n        "fraud_details": {\n          "stripe_report": null,\n          "user_report": null\n        },\n        "id": "ch_3QcS2tAHBUVqiOLM2EHImRY4",\n        "invoice": null,\n        "level3": null,\n        "livemode": false,\n        "metadata": {},\n        "object": "charge",\n        "on_behalf_of": null,\n        "order": null,\n        "outcome": {\n          "network_status": "approved_by_network",\n          "reason": null,\n          "risk_level": "normal",\n          "risk_score": 56,\n          "rule": null,\n          "seller_message": "Payment complete.",\n          "type": "authorized"\n        },\n        "paid": true,\n        "payment_intent": "pi_3QcS2tAHBUVqiOLM2Yh3oVTQ",\n        "payment_method": "pm_1QcS2oAHBUVqiOLMoPyQHwgW",\n        "payment_method_details": {\n          "ach_credit_transfer": null,\n          "ach_debit": null,\n          "acss_debit": null,\n          "afterpay_clearpay": null,\n          "alipay": null,\n          "au_becs_debit": null,\n          "bacs_debit": null,\n          "bancontact": null,\n          "boleto": null,\n          "card": {\n            "brand": "mastercard",\n            "checks": {\n              "address_line1_check": null,\n              "address_postal_code_check": null,\n              "cvc_check": "pass"\n            },\n            "country": "US",\n            "description": null,\n            "exp_month": 4,\n            "exp_year": 2035,\n            "fingerprint": "yGiK8L37nQ0YI2ub",\n            "funding": "credit",\n            "iin": null,\n            "installments": null,\n            "issuer": null,\n            "last4": "4444",\n            "mandate": null,\n            "moto": null,\n            "network": "mastercard",\n            "three_d_secure": null,\n            "wallet": null\n          },\n          "card_present": null,\n          "customer_balance": null,\n          "eps": null,\n          "fpx": null,\n          "giropay": null,\n          "grabpay": null,\n          "ideal": null,\n          "interac_present": null,\n          "klarna": null,\n          "konbini": null,\n          "multibanco": null,\n          "oxxo": null,\n          "p24": null,\n          "paynow": null,\n          "sepa_credit_transfer": null,\n          "sepa_debit": null,\n          "sofort": null,\n          "stripe_account": null,\n          "type": "card",\n          "us_bank_account": null,\n          "wechat": null,\n          "wechat_pay": null\n        },\n        "receipt_email": null,\n        "receipt_number": null,\n        "receipt_url": "https://pay.stripe.com/receipts/payment/CAcaFwoVYWNjdF8xTmljN1dBSEJVVnFpT0xNKJiI1bsGMgZlNilY5Po6LBbZENVYnC8vrjuLldiNIWcrPv2Y6Za1ZAPo0DBcrlSbxzC9aSJHnqgaEFwV",\n        "refunded": false,\n        "refunds": {\n          "object": "list",\n          "data": [],\n          "has_more": false,\n          "url": "/v1/charges/ch_3QcS2tAHBUVqiOLM2EHImRY4/refunds",\n          "request_params": null\n        },\n        "review": null,\n        "shipping": null,\n        "source": null,\n        "source_transfer": null,\n        "statement_descriptor": null,\n        "statement_descriptor_suffix": null,\n        "status": "succeeded",\n        "transfer": null,\n        "transfer_data": null,\n        "transfer_group": null\n      }\n    ],\n    "has_more": false,\n    "url": "/v1/charges?payment_intent=pi_3QcS2tAHBUVqiOLM2Yh3oVTQ",\n    "request_params": null\n  },\n  "client_secret": "pi_3QcS2tAHBUVqiOLM2Yh3oVTQ_secret_G4v2Hyu9B4YeRhJ3EdNc6nyTM",\n  "confirmation_method": "automatic",\n  "created": 1735738391,\n  "currency": "usd",\n  "customer": "cus_Qv7Gln3W3dqssN",\n  "description": null,\n  "id": "pi_3QcS2tAHBUVqiOLM2Yh3oVTQ",\n  "invoice": null,\n  "last_payment_error": null,\n  "livemode": false,\n  "metadata": {},\n  "next_action": null,\n  "object": "payment_intent",\n  "on_behalf_of": null,\n  "payment_method": "pm_1QcS2oAHBUVqiOLMoPyQHwgW",\n  "payment_method_options": {\n    "acss_debit": null,\n    "afterpay_clearpay": null,\n    "alipay": null,\n    "au_becs_debit": null,\n    "bacs_debit": null,\n    "bancontact": null,\n    "boleto": null,\n    "card": {\n      "capture_method": null,\n      "installments": null,\n      "mandate_options": null,\n      "network": null,\n      "request_three_d_secure": "automatic",\n      "setup_future_usage": null\n    },\n    "card_present": null,\n    "customer_balance": null,\n    "eps": null,\n    "fpx": null,\n    "giropay": null,\n    "grabpay": null,\n    "ideal": null,\n    "interac_present": null,\n    "klarna": null,\n    "konbini": null,\n    "oxxo": null,\n    "p24": null,\n    "paynow": null,\n    "sepa_debit": null,\n    "sofort": null,\n    "us_bank_account": null,\n    "wechat_pay": null\n  },\n  "payment_method_types": [\n    "card"\n  ],\n  "processing": null,\n  "receipt_email": null,\n  "review": null,\n  "setup_future_usage": null,\n  "shipping": null,\n  "source": null,\n  "statement_descriptor": null,\n  "statement_descriptor_suffix": null,\n  "status": "succeeded",\n  "transfer_data": null,\n  "transfer_group": null\n}',
                    channelName: null,
                    referenceId: 'ch_3QcS2tAHBUVqiOLM2EHImRY4',
                    collected: true
                },
                {
                    id: 6882,
                    userid: 1429,
                    vehicleid: 34,
                    reservationid: 2260,
                    tripid: 2259,
                    hostid: 1418,
                    trippaymenttokenid: 2352,
                    channelid: 1,
                    stripetoken: 'pi_3QcS2tAHBUVqiOLM2Yh3oVTQ',
                    stripetokenid: 'cus_Qv7Gln3W3dqssN',
                    amount: 541.0,
                    stripestatus: 'succeeded',
                    paymentinitiated: '2025-01-01 13:33:12.256787+00',
                    paymentdate: '2025-01-01 13:33:12.256787+00',
                    createddate: '2025-01-01 13:33:12.256787+00',
                    updateddate: '2025-01-01 13:33:12.256787+00',
                    stripeResponse: null,
                    channelName: null,
                    referenceId: null,
                    collected: false
                },
                {
                    id: 6903,
                    userid: 1429,
                    vehicleid: 34,
                    reservationid: 2259,
                    tripid: 2259,
                    hostid: 1418,
                    trippaymenttokenid: 0,
                    channelid: 1,
                    stripetoken: 'pi_3QcVplAHBUVqiOLM2sLoDD2l',
                    stripetokenid: 'cus_Qv7Gln3W3dqssN',
                    amount: 7329.0,
                    stripestatus: 'succeeded',
                    paymentinitiated: '2025-01-01 17:35:54.765523+00',
                    paymentdate: '2025-01-01 17:35:54.765523+00',
                    createddate: '2025-01-01 17:35:54.765523+00',
                    updateddate: '2025-01-01 17:35:54.765523+00',
                    stripeResponse:
                        '<com.stripe.model.PaymentIntent@1109842402 id=pi_3QcVplAHBUVqiOLM2sLoDD2l> JSON: {\n  "amount": 7329,\n  "amount_capturable": 0,\n  "amount_details": {\n    "tip": {\n      "amount": null\n    }\n  },\n  "amount_received": 7329,\n  "application": null,\n  "application_fee_amount": null,\n  "automatic_payment_methods": null,\n  "canceled_at": null,\n  "cancellation_reason": null,\n  "capture_method": "automatic",\n  "charges": {\n    "object": "list",\n    "data": [\n      {\n        "alternate_statement_descriptors": null,\n        "amount": 7329,\n        "amount_captured": 7329,\n        "amount_refunded": 0,\n        "application": null,\n        "application_fee": null,\n        "application_fee_amount": null,\n        "authorization_code": null,\n        "balance_transaction": "txn_3QcVplAHBUVqiOLM2GHj5n2w",\n        "billing_details": {\n          "address": {\n            "city": null,\n            "country": "IN",\n            "line1": null,\n            "line2": null,\n            "postal_code": null,\n            "state": null\n          },\n          "email": null,\n          "name": null,\n          "phone": null\n        },\n        "calculated_statement_descriptor": "WWW.MYBUNDEE.COM",\n        "captured": true,\n        "created": 1735752954,\n        "currency": "usd",\n        "customer": "cus_Qv7Gln3W3dqssN",\n        "description": null,\n        "destination": null,\n        "dispute": null,\n        "disputed": false,\n        "failure_balance_transaction": null,\n        "failure_code": null,\n        "failure_message": null,\n        "fraud_details": {\n          "stripe_report": null,\n          "user_report": null\n        },\n        "id": "ch_3QcVplAHBUVqiOLM2UyQ4S6n",\n        "invoice": null,\n        "level3": null,\n        "livemode": false,\n        "metadata": {},\n        "object": "charge",\n        "on_behalf_of": null,\n        "order": null,\n        "outcome": {\n          "network_status": "approved_by_network",\n          "reason": null,\n          "risk_level": "normal",\n          "risk_score": 17,\n          "rule": null,\n          "seller_message": "Payment complete.",\n          "type": "authorized"\n        },\n        "paid": true,\n        "payment_intent": "pi_3QcVplAHBUVqiOLM2sLoDD2l",\n        "payment_method": "pm_1QcS2oAHBUVqiOLMoPyQHwgW",\n        "payment_method_details": {\n          "ach_credit_transfer": null,\n          "ach_debit": null,\n          "acss_debit": null,\n          "afterpay_clearpay": null,\n          "alipay": null,\n          "au_becs_debit": null,\n          "bacs_debit": null,\n          "bancontact": null,\n          "boleto": null,\n          "card": {\n            "brand": "mastercard",\n            "checks": {\n              "address_line1_check": null,\n              "address_postal_code_check": null,\n              "cvc_check": null\n            },\n            "country": "US",\n            "description": null,\n            "exp_month": 4,\n            "exp_year": 2035,\n            "fingerprint": "yGiK8L37nQ0YI2ub",\n            "funding": "credit",\n            "iin": null,\n            "installments": null,\n            "issuer": null,\n            "last4": "4444",\n            "mandate": null,\n            "moto": null,\n            "network": "mastercard",\n            "three_d_secure": null,\n            "wallet": null\n          },\n          "card_present": null,\n          "customer_balance": null,\n          "eps": null,\n          "fpx": null,\n          "giropay": null,\n          "grabpay": null,\n          "ideal": null,\n          "interac_present": null,\n          "klarna": null,\n          "konbini": null,\n          "multibanco": null,\n          "oxxo": null,\n          "p24": null,\n          "paynow": null,\n          "sepa_credit_transfer": null,\n          "sepa_debit": null,\n          "sofort": null,\n          "stripe_account": null,\n          "type": "card",\n          "us_bank_account": null,\n          "wechat": null,\n          "wechat_pay": null\n        },\n        "receipt_email": null,\n        "receipt_number": null,\n        "receipt_url": "https://pay.stripe.com/receipts/payment/CAcaFwoVYWNjdF8xTmljN1dBSEJVVnFpT0xNKPr51bsGMgbxQe9hK8w6LBYkqGi6i9bAJzl7tQGj-FWRzmLQzauP2Wlf9rWKE5eHpjDRTpr9U-hTfECs",\n        "refunded": false,\n        "refunds": {\n          "object": "list",\n          "data": [],\n          "has_more": false,\n          "url": "/v1/charges/ch_3QcVplAHBUVqiOLM2UyQ4S6n/refunds",\n          "request_params": null\n        },\n        "review": null,\n        "shipping": null,\n        "source": null,\n        "source_transfer": null,\n        "statement_descriptor": null,\n        "statement_descriptor_suffix": null,\n        "status": "succeeded",\n        "transfer": null,\n        "transfer_data": null,\n        "transfer_group": null\n      }\n    ],\n    "has_more": false,\n    "url": "/v1/charges?payment_intent=pi_3QcVplAHBUVqiOLM2sLoDD2l",\n    "request_params": null\n  },\n  "client_secret": "pi_3QcVplAHBUVqiOLM2sLoDD2l_secret_HkI58csTPK56eewBEuVK0SenK",\n  "confirmation_method": "automatic",\n  "created": 1735752953,\n  "currency": "usd",\n  "customer": "cus_Qv7Gln3W3dqssN",\n  "description": null,\n  "id": "pi_3QcVplAHBUVqiOLM2sLoDD2l",\n  "invoice": null,\n  "last_payment_error": null,\n  "livemode": false,\n  "metadata": {},\n  "next_action": null,\n  "object": "payment_intent",\n  "on_behalf_of": null,\n  "payment_method": "pm_1QcS2oAHBUVqiOLMoPyQHwgW",\n  "payment_method_options": {\n    "acss_debit": null,\n    "afterpay_clearpay": null,\n    "alipay": null,\n    "au_becs_debit": null,\n    "bacs_debit": null,\n    "bancontact": null,\n    "boleto": null,\n    "card": {\n      "capture_method": null,\n      "installments": null,\n      "mandate_options": null,\n      "network": null,\n      "request_three_d_secure": "automatic",\n      "setup_future_usage": null\n    },\n    "card_present": null,\n    "customer_balance": null,\n    "eps": null,\n    "fpx": null,\n    "giropay": null,\n    "grabpay": null,\n    "ideal": null,\n    "interac_present": null,\n    "klarna": null,\n    "konbini": null,\n    "oxxo": null,\n    "p24": null,\n    "paynow": null,\n    "sepa_debit": null,\n    "sofort": null,\n    "us_bank_account": null,\n    "wechat_pay": null\n  },\n  "payment_method_types": [\n    "card"\n  ],\n  "processing": null,\n  "receipt_email": null,\n  "review": null,\n  "setup_future_usage": null,\n  "shipping": null,\n  "source": null,\n  "statement_descriptor": null,\n  "statement_descriptor_suffix": null,\n  "status": "succeeded",\n  "transfer_data": null,\n  "transfer_group": null\n}',
                    channelName: null,
                    referenceId: 'ch_3QcVplAHBUVqiOLM2UyQ4S6n',
                    collected: true
                },
                {
                    id: 6904,
                    userid: 1429,
                    vehicleid: 34,
                    reservationid: 2260,
                    tripid: 2259,
                    hostid: 1418,
                    trippaymenttokenid: 2352,
                    channelid: 1,
                    stripetoken: 'pi_3QcVplAHBUVqiOLM2sLoDD2l',
                    stripetokenid: 'cus_Qv7Gln3W3dqssN',
                    amount: 7329.0,
                    stripestatus: 'succeeded',
                    paymentinitiated: '2025-01-01 17:35:54.774718+00',
                    paymentdate: '2025-01-01 17:35:54.774718+00',
                    createddate: '2025-01-01 17:35:54.774718+00',
                    updateddate: '2025-01-01 17:35:54.774718+00',
                    stripeResponse: null,
                    channelName: null,
                    referenceId: null,
                    collected: false
                },
                {
                    id: 6905,
                    userid: 1429,
                    vehicleid: 34,
                    reservationid: 2259,
                    tripid: 2259,
                    hostid: 1418,
                    trippaymenttokenid: 0,
                    channelid: 1,
                    stripetoken: 'pi_3QcWSgAHBUVqiOLM34UWIlkB',
                    stripetokenid: 'cus_Qv7Gln3W3dqssN',
                    amount: 758.0,
                    stripestatus: 'succeeded',
                    paymentinitiated: '2025-01-01 18:16:07.115887+00',
                    paymentdate: '2025-01-01 18:16:07.115887+00',
                    createddate: '2025-01-01 18:16:07.115887+00',
                    updateddate: '2025-01-01 18:16:07.115887+00',
                    stripeResponse:
                        '<com.stripe.model.PaymentIntent@420612621 id=pi_3QcWSgAHBUVqiOLM34UWIlkB> JSON: {\n  "amount": 758,\n  "amount_capturable": 0,\n  "amount_details": {\n    "tip": {\n      "amount": null\n    }\n  },\n  "amount_received": 758,\n  "application": null,\n  "application_fee_amount": null,\n  "automatic_payment_methods": null,\n  "canceled_at": null,\n  "cancellation_reason": null,\n  "capture_method": "automatic",\n  "charges": {\n    "object": "list",\n    "data": [\n      {\n        "alternate_statement_descriptors": null,\n        "amount": 758,\n        "amount_captured": 758,\n        "amount_refunded": 0,\n        "application": null,\n        "application_fee": null,\n        "application_fee_amount": null,\n        "authorization_code": null,\n        "balance_transaction": "txn_3QcWSgAHBUVqiOLM3lyw3ZVy",\n        "billing_details": {\n          "address": {\n            "city": null,\n            "country": "IN",\n            "line1": null,\n            "line2": null,\n            "postal_code": null,\n            "state": null\n          },\n          "email": null,\n          "name": null,\n          "phone": null\n        },\n        "calculated_statement_descriptor": "WWW.MYBUNDEE.COM",\n        "captured": true,\n        "created": 1735755366,\n        "currency": "usd",\n        "customer": "cus_Qv7Gln3W3dqssN",\n        "description": null,\n        "destination": null,\n        "dispute": null,\n        "disputed": false,\n        "failure_balance_transaction": null,\n        "failure_code": null,\n        "failure_message": null,\n        "fraud_details": {\n          "stripe_report": null,\n          "user_report": null\n        },\n        "id": "ch_3QcWSgAHBUVqiOLM3XJyn3Rg",\n        "invoice": null,\n        "level3": null,\n        "livemode": false,\n        "metadata": {},\n        "object": "charge",\n        "on_behalf_of": null,\n        "order": null,\n        "outcome": {\n          "network_status": "approved_by_network",\n          "reason": null,\n          "risk_level": "normal",\n          "risk_score": 40,\n          "rule": null,\n          "seller_message": "Payment complete.",\n          "type": "authorized"\n        },\n        "paid": true,\n        "payment_intent": "pi_3QcWSgAHBUVqiOLM34UWIlkB",\n        "payment_method": "pm_1QcS2oAHBUVqiOLMoPyQHwgW",\n        "payment_method_details": {\n          "ach_credit_transfer": null,\n          "ach_debit": null,\n          "acss_debit": null,\n          "afterpay_clearpay": null,\n          "alipay": null,\n          "au_becs_debit": null,\n          "bacs_debit": null,\n          "bancontact": null,\n          "boleto": null,\n          "card": {\n            "brand": "mastercard",\n            "checks": {\n              "address_line1_check": null,\n              "address_postal_code_check": null,\n              "cvc_check": null\n            },\n            "country": "US",\n            "description": null,\n            "exp_month": 4,\n            "exp_year": 2035,\n            "fingerprint": "yGiK8L37nQ0YI2ub",\n            "funding": "credit",\n            "iin": null,\n            "installments": null,\n            "issuer": null,\n            "last4": "4444",\n            "mandate": null,\n            "moto": null,\n            "network": "mastercard",\n            "three_d_secure": null,\n            "wallet": null\n          },\n          "card_present": null,\n          "customer_balance": null,\n          "eps": null,\n          "fpx": null,\n          "giropay": null,\n          "grabpay": null,\n          "ideal": null,\n          "interac_present": null,\n          "klarna": null,\n          "konbini": null,\n          "multibanco": null,\n          "oxxo": null,\n          "p24": null,\n          "paynow": null,\n          "sepa_credit_transfer": null,\n          "sepa_debit": null,\n          "sofort": null,\n          "stripe_account": null,\n          "type": "card",\n          "us_bank_account": null,\n          "wechat": null,\n          "wechat_pay": null\n        },\n        "receipt_email": null,\n        "receipt_number": null,\n        "receipt_url": "https://pay.stripe.com/receipts/payment/CAcaFwoVYWNjdF8xTmljN1dBSEJVVnFpT0xNKOaM1rsGMgb8Jb9sv-86LBau3GovZZsRSJ-SgQFnXQUAVMNAovhghi_h1W0Tb5Y07e9of1RFkS_4k8fE",\n        "refunded": false,\n        "refunds": {\n          "object": "list",\n          "data": [],\n          "has_more": false,\n          "url": "/v1/charges/ch_3QcWSgAHBUVqiOLM3XJyn3Rg/refunds",\n          "request_params": null\n        },\n        "review": null,\n        "shipping": null,\n        "source": null,\n        "source_transfer": null,\n        "statement_descriptor": null,\n        "statement_descriptor_suffix": null,\n        "status": "succeeded",\n        "transfer": null,\n        "transfer_data": null,\n        "transfer_group": null\n      }\n    ],\n    "has_more": false,\n    "url": "/v1/charges?payment_intent=pi_3QcWSgAHBUVqiOLM34UWIlkB",\n    "request_params": null\n  },\n  "client_secret": "pi_3QcWSgAHBUVqiOLM34UWIlkB_secret_qfxjtcufuQA6NkY2hi8KGgfbI",\n  "confirmation_method": "automatic",\n  "created": 1735755366,\n  "currency": "usd",\n  "customer": "cus_Qv7Gln3W3dqssN",\n  "description": null,\n  "id": "pi_3QcWSgAHBUVqiOLM34UWIlkB",\n  "invoice": null,\n  "last_payment_error": null,\n  "livemode": false,\n  "metadata": {},\n  "next_action": null,\n  "object": "payment_intent",\n  "on_behalf_of": null,\n  "payment_method": "pm_1QcS2oAHBUVqiOLMoPyQHwgW",\n  "payment_method_options": {\n    "acss_debit": null,\n    "afterpay_clearpay": null,\n    "alipay": null,\n    "au_becs_debit": null,\n    "bacs_debit": null,\n    "bancontact": null,\n    "boleto": null,\n    "card": {\n      "capture_method": null,\n      "installments": null,\n      "mandate_options": null,\n      "network": null,\n      "request_three_d_secure": "automatic",\n      "setup_future_usage": null\n    },\n    "card_present": null,\n    "customer_balance": null,\n    "eps": null,\n    "fpx": null,\n    "giropay": null,\n    "grabpay": null,\n    "ideal": null,\n    "interac_present": null,\n    "klarna": null,\n    "konbini": null,\n    "oxxo": null,\n    "p24": null,\n    "paynow": null,\n    "sepa_debit": null,\n    "sofort": null,\n    "us_bank_account": null,\n    "wechat_pay": null\n  },\n  "payment_method_types": [\n    "card"\n  ],\n  "processing": null,\n  "receipt_email": null,\n  "review": null,\n  "setup_future_usage": null,\n  "shipping": null,\n  "source": null,\n  "statement_descriptor": null,\n  "statement_descriptor_suffix": null,\n  "status": "succeeded",\n  "transfer_data": null,\n  "transfer_group": null\n}',
                    channelName: null,
                    referenceId: 'ch_3QcWSgAHBUVqiOLM3XJyn3Rg',
                    collected: true
                },
                {
                    id: 6906,
                    userid: 1429,
                    vehicleid: 34,
                    reservationid: 2260,
                    tripid: 2259,
                    hostid: 1418,
                    trippaymenttokenid: 2352,
                    channelid: 1,
                    stripetoken: 'pi_3QcWSgAHBUVqiOLM34UWIlkB',
                    stripetokenid: 'cus_Qv7Gln3W3dqssN',
                    amount: 758.0,
                    stripestatus: 'succeeded',
                    paymentinitiated: '2025-01-01 18:16:07.123951+00',
                    paymentdate: '2025-01-01 18:16:07.123951+00',
                    createddate: '2025-01-01 18:16:07.123951+00',
                    updateddate: '2025-01-01 18:16:07.123951+00',
                    stripeResponse: null,
                    channelName: null,
                    referenceId: null,
                    collected: false
                }
            ],
            cancelresponse: [],
            tripSlipPayments: [],
            rentalCharges: [],
            tripChargeLedgers: [],
            paymentCaptures: [],
            tripPayementAuthResponses: [],
            vehicleDetails: [
                {
                    id: 34,
                    vin: '1G1FW6S09H4185736',
                    make: 'CHEVROLET',
                    model: 'Bolt EV',
                    desciption: 'Electric car',
                    year: '2017',
                    cityname: 'Austin',
                    price_per_hr: 30,
                    latitude: '30.30113275013598',
                    longitude: '-97.7703724900501',
                    address1: 'tarryTown',
                    address2: '',
                    zipcode: '73301',
                    state: 'Texas',
                    name: 'Electric',
                    bedtype: 'Not Applicable',
                    bodyclass: 'Hatchback/Liftback/Notchback',
                    busfloortype: 'Not Applicable',
                    bustype: 'Not Applicable',
                    cabtype: 'Not Applicable',
                    custommotortype: 'Not Applicable',
                    doors: '4',
                    drivetype: '',
                    wlectrificationlevel: null,
                    enginebrake: '',
                    enginepower: '',
                    frontairbaglocation: '1st Row (Driver and Passenger)',
                    fueltypeprimary: 'Electric',
                    manufacturename: 'GENERAL MOTORS LLC',
                    motorcyclechasistype: 'Not Applicable',
                    motorcyclesuspensiontype: 'Not Applicable',
                    othetengineinfo: null,
                    OtherRestraintSystemInfo: 'AYF - Active Manual Belts',
                    plantCity: 'ORION',
                    plantCompanyName: '',
                    plantCountry: 'UNITED STATES (USA)',
                    plantstate: 'MICHIGAN',
                    seatbelttype: 'Manual',
                    SideAirBagLocations: '1st and 2nd Rows',
                    SteeringLocation: '',
                    tirePressure: 'Direct',
                    trailerBodyType: 'Not Applicable',
                    trailerTypeConnection: 'Not Applicable',
                    trim: '',
                    turbo: null,
                    vehicleType: 'PASSENGER CAR',
                    count: 0,
                    tripcount: 2,
                    rating: 4.0,
                    wishList: false,
                    vehicleDescription: null,
                    seatingCapacity: null,
                    insuranceHeader: null,
                    insuranceHeaderType: null,
                    insuranceDetails1: null,
                    insuranceDetails2: null,
                    insuranceDetails3: null,
                    parkingDetails: null,
                    guideLines: null,
                    policies: null,
                    imageresponse: [
                        {
                            idimage: 114,
                            orderNumber: 1,
                            isPrimary: true,
                            vehicleid: 34,
                            imagename: 'https://fiat.b-cdn.net/H4185736.jpeg',
                            userid: 1,
                            isactive: true,
                            createdate: '2023-11-07 14:22:52.995225+00',
                            updatedate: '2023-11-07 14:22:52.995225+00',
                            imageUuid: null
                        }
                    ],
                    tripreview: [
                        {
                            reviewid: 26,
                            reservationid: 863,
                            vehicleid: 34,
                            userid: 1429,
                            rating: 4,
                            tripid: 863,
                            avg: 0.0,
                            comments: 'Good',
                            createddate: '2024-06-17 14:57:01.555075+00',
                            updateddate: '2024-06-17 14:57:01.555075+00',
                            isactive: true,
                            hostId: 0
                        }
                    ]
                }
            ],
            tripModificationDetails: [],
            tripStatusTransactionResponses: [
                {
                    id: 144346,
                    tripid: 2259,
                    reservationid: 2260,
                    userid: 0,
                    vehicleid: 34,
                    hostid: 0,
                    channelid: 1,
                    fromstatus: 'Uncaptured',
                    tostatus: 'CaptureSuccessful',
                    changedby: null,
                    isactive: true,
                    createddate: '2025-01-01 13:33:12.239701+00',
                    updatedate: null,
                    comments: 'Collected $5.41  from  creditcard mastercard ending with ****4444',
                    createdBy: null,
                    viewed: false,
                    rentalAgrrementStatus: '',
                    isRentalStatus: false,
                    modificationId: 0,
                    metaData: null,
                    isEventmessageConfigured: false,
                    eventMessage: null
                },
                {
                    id: 144349,
                    tripid: 2259,
                    reservationid: 2260,
                    userid: 0,
                    vehicleid: 34,
                    hostid: 0,
                    channelid: 1,
                    fromstatus: 'No booking',
                    tostatus: 'REREQ',
                    changedby: 'USER',
                    isactive: true,
                    createddate: '2025-01-01 13:33:12.280393+00',
                    updatedate: null,
                    comments: 'Reservation was created',
                    createdBy: null,
                    viewed: false,
                    rentalAgrrementStatus: '',
                    isRentalStatus: false,
                    modificationId: 0,
                    metaData: null,
                    isEventmessageConfigured: false,
                    eventMessage: null
                },
                {
                    id: 144424,
                    tripid: 2259,
                    reservationid: 2260,
                    userid: 0,
                    vehicleid: 34,
                    hostid: 0,
                    channelid: 1,
                    fromstatus: 'Uncaptured',
                    tostatus: 'CaptureSuccessful',
                    changedby: 'HOST',
                    isactive: true,
                    createddate: '2025-01-01 17:35:54.760182+00',
                    updatedate: null,
                    comments: 'Collected $73.29  from  creditcard mastercard ending with ****4444',
                    createdBy: null,
                    viewed: false,
                    rentalAgrrementStatus: '',
                    isRentalStatus: false,
                    modificationId: 0,
                    metaData: null,
                    isEventmessageConfigured: false,
                    eventMessage: null
                },
                {
                    id: 144427,
                    tripid: 2259,
                    reservationid: 2260,
                    userid: 0,
                    vehicleid: 34,
                    hostid: 0,
                    channelid: 1,
                    fromstatus: 'REREQ',
                    tostatus: 'REAPP',
                    changedby: 'HOST',
                    isactive: true,
                    createddate: '2025-01-01 17:35:54.835304+00',
                    updatedate: null,
                    comments: 'The trip has been Approved.',
                    createdBy: null,
                    viewed: false,
                    rentalAgrrementStatus: 'The trip has been Approved.',
                    isRentalStatus: true,
                    modificationId: 0,
                    metaData: null,
                    isEventmessageConfigured: false,
                    eventMessage: 'The trip has been Approved.'
                },
                {
                    id: 144430,
                    tripid: 2259,
                    reservationid: 2260,
                    userid: 0,
                    vehicleid: 34,
                    hostid: 0,
                    channelid: 1,
                    fromstatus: 'REREQ',
                    tostatus: 'REAPP',
                    changedby: 'HOST',
                    isactive: true,
                    createddate: '2025-01-01 17:35:57.965161+00',
                    updatedate: null,
                    comments: 'The trip has been Approved.',
                    createdBy: null,
                    viewed: false,
                    rentalAgrrementStatus: 'The trip has been Approved.',
                    isRentalStatus: true,
                    modificationId: 0,
                    metaData: null,
                    isEventmessageConfigured: true,
                    eventMessage:
                        'Hi there Gagan, Welcome to the world of Electric Vehicles!\n\nThis Bolt is a fully Electric car with about 200+ miles of range average. Charging takes time - some charge overnight, some use DC Fast chargers, it is completely up to you.\n\nAustin has tons of chargers, as do most of the major metro centers nearby. You get access to our app, a great help to find available chargers you can use. Here in Austin, you can get free L2 charging with a card that’ll be attached to your key.\n\nThat said, I don’t recommend the car for your long road trips, or for leaving the state. The charger network in America is just not to that point yet.\n\nI do all my rentals via contactless handoff. You’ll never see me, but you’re welcome to message me through here with questions.\n\nThanks for renting with me!'
                },
                {
                    id: 144433,
                    tripid: 2259,
                    reservationid: 2260,
                    userid: 0,
                    vehicleid: 34,
                    hostid: 0,
                    channelid: 1,
                    fromstatus: 'REAPP',
                    tostatus: 'TRSTR',
                    changedby: 'HOST',
                    isactive: true,
                    createddate: '2025-01-01 17:36:35.962866+00',
                    updatedate: null,
                    comments: 'The trip has been Started.',
                    createdBy: null,
                    viewed: false,
                    rentalAgrrementStatus: 'The trip has been Started.',
                    isRentalStatus: true,
                    modificationId: 0,
                    metaData: null,
                    isEventmessageConfigured: false,
                    eventMessage: 'The trip has been Started.'
                },
                {
                    id: 144436,
                    tripid: 2259,
                    reservationid: 2260,
                    userid: 0,
                    vehicleid: 34,
                    hostid: 0,
                    channelid: 1,
                    fromstatus: 'TRSTR',
                    tostatus: 'TRCOM',
                    changedby: 'HOST',
                    isactive: true,
                    createddate: '2025-01-01 18:13:10.863265+00',
                    updatedate: null,
                    comments: 'The trip has been Completed.',
                    createdBy: null,
                    viewed: false,
                    rentalAgrrementStatus: 'The trip has been Completed.',
                    isRentalStatus: true,
                    modificationId: 0,
                    metaData: null,
                    isEventmessageConfigured: false,
                    eventMessage: 'The trip has been Completed.'
                },
                {
                    id: 144439,
                    tripid: 2259,
                    reservationid: 2260,
                    userid: 0,
                    vehicleid: 34,
                    hostid: 0,
                    channelid: 1,
                    fromstatus: 'Uncaptured',
                    tostatus: 'CaptureSuccessful',
                    changedby: 'HOST',
                    isactive: true,
                    createddate: '2025-01-01 18:16:07.108663+00',
                    updatedate: null,
                    comments: 'Collected $7.58  from  creditcard mastercard ending with ****4444',
                    createdBy: null,
                    viewed: false,
                    rentalAgrrementStatus: '',
                    isRentalStatus: false,
                    modificationId: 0,
                    metaData: null,
                    isEventmessageConfigured: false,
                    eventMessage: null
                }
            ],
            transactionCheckLists: [],
            tripConstraints: [
                {
                    id: 2165,
                    upcharges: 0,
                    mileageconstraint: 676,
                    minmaxdays: 140,
                    discounts: 639,
                    deliverydetails: 0,
                    guestinstructionandguidelines: 0,
                    tripId: 2259,
                    vehicleId: 34,
                    isActive: true,
                    amountCaptured: 0.0,
                    extraCharges: 0.0,
                    tripAmount: 0.0,
                    extraMileageCost: 0.0,
                    extraMilage: 0.0
                }
            ],
            hostTripStartingBlobs: [],
            hostTripCompletingBlobs: [],
            driverTripStartingBlobs: [],
            driverTripCompletingBlobs: [],
            cancellationRequestedMessage: null,
            cancellationRequested: false,
            depositToBeCollected: true,
            depositToBeCollectedForTrip: true,
            depositRenewFailed: false,
            debitHoldReleased: false,
            closingMilesEntered: false,
            extraChargesEntered: true,
            isCardExtensionFailed: false,
            cardExtensionFailedReason: null,
            failedtripextensionmessage: null,
            failedautotripExtension: false,
            userImage: 'https://bundeestorage.blob.core.windows.net/bundeeqastorage/%2F1429%2F8ea3422dbcd047d487a572bdbeb7d258.jpg',
            completedDate: '2025-01-01 18:13:13.702+00',
            userEmail: 'gagankumar8711@gmail.com',
            userMobilePhone: '+1234523455',
            invoiceUrl: 'https://bundeestorage.blob.core.windows.net/bundeeqastorage/Receipt2259.pdf',
            rentalAgrrementUrl: 'https://bundeestorage.blob.core.windows.net/bundeeqastorage/RentalAgreement2259.pdf',
            paymentFailedReason: null,
            paymentFailed: false,
            is24HoursBooking: false,
            tripid: 2259,
            statusCode: 'TRCOM',
            reservationid: 2260,
            actualstarttime: null,
            actualendttime: null,
            tripstatus: 4,
            openingMiles: 400.0,
            closingMiles: 4646.0,
            userid: 1429,
            vehicleId: 34,
            channelId: 1,
            isactive: true,
            newRequest: false,
            startFailed: false,
            failedDriverVerifications: false,
            newRequestMessage: null,
            startFailedMessage: null,
            failedDriverVerificationsMessage: null,
            createddate: '2025-01-01 13:33:10.707888+00',
            updateddate: '2025-01-01 18:13:10.867+00',
            hostid: 1418,
            starttime: '2025-01-03 04:00:00+00',
            endtime: '2025-01-05 04:00:00+00',
            status: 'Completed',
            tripCount: '3',
            pickupLocation: 'NA',
            logCompleted: 'false',
            unreadMsgCount: '0',
            vehmake: 'CHEVROLET',
            vehmodel: 'Bolt EV',
            vehyear: '2017',
            vehcityname: 'Austin',
            vehzipcode: '73301',
            vehaddress1: 'tarryTown',
            vehaddress2: '',
            vehstate: 'Texas',
            userFirstName: 'Gagan',
            userlastName: 'Test',
            cancellationDays: 2,
            bookingId: 'BUN202510084a08f22-49bc-4623-9ae9-33bccf46a56e',
            message: null,
            colorCode: '#34A853',
            channelName: 'Bundee',
            delivery: false,
            airportDelivery: false,
            isRentalAgreed: false,
            rentalAgreedDate: '2025-01-01 13:33:10.707888+00',
            vehicleNumber: '134688',
            hostFirstName: 'Bundee Fleet',
            hostLastName: 'Test',
            hostPhoneNumber: '5125797470',
            hostImage: 'https://bundeestorage.blob.core.windows.net/bundeeqastorage/%2F1418%2F0f1b0eda5c7944f698e628b2ca302567.jpg',
            isLicenseVerified: true,
            drivingLicenseStatus: 'verified',
            isInsuranceVerified: false,
            insuranceStatus: null,
            isPhoneVarified: true
        }
    ],
    cancellationRequestedTrips: [],
    failedToStartTrips: [],
    failedTripExtensions: [],
    failedCardExtensions: null,
    failedPayments: [],
    newRequests: [],
    failedDriverVerifications: [],
    locationResponses: [],
    activeTrips: [],
    userResponses: null,
    vehicles: null,
    paymentTransactions: [],
    tripreview: [],
    tripresponse: [],
    imageresponse: [],
    channels: [],
    tripPaymentTokens: [],
    reservationresponse: null,
    deductionFrequencyConfigs: [],
    pdfResponses: [],
    count: 0,
    deductionFrequencyDays: null,
    paymentRequests: [],
    deductionEventConfig: [],
    deductionDetails: [],
    paymentAuthorizationCategories: [],
    tripPaymentCategories: [],
    paymentAuthConfigs: [],
    paymentCaptures: [],
    capturedPaymentToken: [],
    cancellationResponses: [],
    authorisationPerResponses: [],
    tripModificationTypes: [],
    tripModificationDetails: [],
    trippaymentcategorymappingResponses: [],
    tripModificationResponses: [],
    tripSlipPayments: [],
    paymentInvoices: [],
    hostInsights: [],
    vehicleAllDetails: [],
    pushnotifications: [],
    statusTransactions: [],
    tripPayementAuthResponses: null,
    masterCheckListTypes: [],
    masterCheckLists: [],
    hostCheckListMappings: [],
    transactionCheckLists: [],
    hostRatingDetails: [],
    hostModificationResponses: [],
    paymentPendings: [],
    tripStatusTransactionResponses: null,
    channelRegistrations: [],
    userVehicleBookings: [],
    tripModificationHistories: [],
    tripPaymentHistoryList: [],
    priceCalculatedList: [],
    driverActivities: [],
    apiMapBoxMAppingResponses: [],
    driverProfiles: [],
    sendGRidRests: [],
    depositHoldConfigurations: [],
    sendGridResponses: [],
    locations: null,
    vehicleBusinessConstraints: [],
    tripMediaFilesResponses: [],
    hostTripStartingBlobs: [],
    hostTripCompletingBlobs: [],
    driverTripStartingBlobs: [],
    driverTripCompletingBlobs: [],
    messageNotifications: [],
    ids: [],
    failedIds: [],
    userTripDetails: [],
    autoExtensionResponses: [],
    failedTuroTripsList: [],
    driverUpcomingTripsResponses: [],
    driverTripDetails: [],
    driverUpComingTrips: [],
    driverTripsCounts: [],
    driverRentalAmounts: [],
    driverOnGoingTripResponse: [],
    chargeTypes: [],
    collectionStatusList: [
        {
            id: 1,
            statusName: 'Future'
        },
        {
            id: 3,
            statusName: 'Pending'
        },
        {
            id: 4,
            statusName: 'Failed'
        },
        {
            id: 5,
            statusName: 'Refunded'
        },
        {
            id: 2,
            statusName: 'Collected'
        },
        {
            id: 6,
            statusName: 'Deposit_hold'
        }
    ],
    tripChargeLedgerList: [
        {
            id: 7440823,
            typeCode: 'TripFee',
            typeDescription: 'platformfee',
            chargeAmount: 5.0,
            chargeTax: 0.412499994,
            chargeTotal: 5.4124999,
            collectionDeadLine: '2025-01-01 04:00:00+00',
            collectionStatusId: 2,
            isPreTripCharge: true,
            isDebt: true,
            isDiscount: false,
            createdDate: '2025-01-01 13:33:10.941119+00',
            bookingId: 2259,
            userId: 1429,
            hostId: 1418,
            collectedDate: '2025-01-01 13:33:12.263+00',
            chargesId: 'ch_3QcS2tAHBUVqiOLM2EHImRY4',
            code: '0-0000',
            collectionAllowed: false,
            isTripChargesRefund: false
        },
        {
            id: 7440824,
            typeCode: 'Upcharges',
            typeDescription: 'Short notice fees',
            chargeAmount: 0.0,
            chargeTax: 0.0,
            chargeTotal: 0.0,
            collectionDeadLine: '2025-01-01 04:00:00+00',
            collectionStatusId: 2,
            isPreTripCharge: true,
            isDebt: true,
            isDiscount: false,
            createdDate: '2025-01-01 13:33:10.941119+00',
            bookingId: 2259,
            userId: 1429,
            hostId: 1418,
            collectedDate: '2025-01-01 17:35:54.793+00',
            chargesId: 'ch_3QcVplAHBUVqiOLM2UyQ4S6n',
            code: '0-0011',
            collectionAllowed: true,
            isTripChargesRefund: false
        },
        {
            id: 7440825,
            typeCode: 'AirportDeliveryCharge',
            typeDescription: 'Airport delivery charge',
            chargeAmount: 0.0,
            chargeTax: 0.0,
            chargeTotal: 0.0,
            collectionDeadLine: '2025-01-01 04:00:00+00',
            collectionStatusId: 2,
            isPreTripCharge: true,
            isDebt: true,
            isDiscount: false,
            createdDate: '2025-01-01 13:33:10.941119+00',
            bookingId: 2259,
            userId: 1429,
            hostId: 1418,
            collectedDate: '2025-01-01 17:35:54.793+00',
            chargesId: 'ch_3QcVplAHBUVqiOLM2UyQ4S6n',
            code: '0-0010',
            collectionAllowed: true,
            isTripChargesRefund: false
        },
        {
            id: 7440826,
            typeCode: 'NonAirportDeliveryCharge',
            typeDescription: 'Non airport delivery charge',
            chargeAmount: 0.0,
            chargeTax: 0.0,
            chargeTotal: 0.0,
            collectionDeadLine: '2025-01-01 04:00:00+00',
            collectionStatusId: 2,
            isPreTripCharge: true,
            isDebt: true,
            isDiscount: false,
            createdDate: '2025-01-01 13:33:10.941119+00',
            bookingId: 2259,
            userId: 1429,
            hostId: 1418,
            collectedDate: '2025-01-01 17:35:54.793+00',
            chargesId: 'ch_3QcVplAHBUVqiOLM2UyQ4S6n',
            code: '0-0001',
            collectionAllowed: true,
            isTripChargesRefund: false
        },
        {
            id: 7440839,
            typeCode: 'CleaningCharges',
            typeDescription: 'Cleaning charges',
            chargeAmount: 0.0,
            chargeTax: 0.0,
            chargeTotal: 0.0,
            collectionDeadLine: '2025-01-01 18:16:05.727+00',
            collectionStatusId: 2,
            isPreTripCharge: true,
            isDebt: true,
            isDiscount: false,
            createdDate: '2025-01-01 18:16:05.743877+00',
            bookingId: 2259,
            userId: 1429,
            hostId: 1418,
            collectedDate: '2025-01-01 18:16:07.139+00',
            chargesId: 'ch_3QcWSgAHBUVqiOLM3XJyn3Rg',
            code: '2-0010',
            collectionAllowed: false,
            isTripChargesRefund: false
        },
        {
            id: 7440840,
            typeCode: 'LateFees',
            typeDescription: 'Late fees',
            chargeAmount: 5.0,
            chargeTax: 0.412499994,
            chargeTotal: 5.4124999,
            collectionDeadLine: '2025-01-01 18:16:05.727+00',
            collectionStatusId: 2,
            isPreTripCharge: true,
            isDebt: true,
            isDiscount: false,
            createdDate: '2025-01-01 18:16:05.743877+00',
            bookingId: 2259,
            userId: 1429,
            hostId: 1418,
            collectedDate: '2025-01-01 18:16:07.139+00',
            chargesId: 'ch_3QcWSgAHBUVqiOLM3XJyn3Rg',
            code: '2-0001',
            collectionAllowed: false,
            isTripChargesRefund: false
        },
        {
            id: 7440841,
            typeCode: 'ExtraDayCharges',
            typeDescription: 'Extra Day Charges',
            chargeAmount: 2.0,
            chargeTax: 0.165000007,
            chargeTotal: 2.16499996,
            collectionDeadLine: '2025-01-01 18:16:05.727+00',
            collectionStatusId: 2,
            isPreTripCharge: true,
            isDebt: true,
            isDiscount: false,
            createdDate: '2025-01-01 18:16:05.743877+00',
            bookingId: 2259,
            userId: 1429,
            hostId: 1418,
            collectedDate: '2025-01-01 18:16:07.139+00',
            chargesId: 'ch_3QcWSgAHBUVqiOLM3XJyn3Rg',
            code: '2-0100',
            collectionAllowed: false,
            isTripChargesRefund: false
        }
    ],
    rentalCharges: [
        {
            isCardChange: false,
            id: 22179,
            chargeAmount: 30.0,
            chargeTax: 2.79262495,
            chargeTotal: 33.8499985,
            collectionDeadLine: '2025-01-01 04:00:00+00',
            rentalDate: '2025-01-03 04:00:00+00',
            collectionStatusId: 2,
            isDebt: true,
            toBeConsidered: true,
            isDiscount: false,
            createdDate: '2025-01-01 13:33:10.953271+00',
            chargesId: 'ch_3QcVplAHBUVqiOLM2UyQ4S6n',
            bookingId: 2259,
            userId: 1429,
            hostId: 1418,
            total: 36.6426239,
            registrationRecoveryFee: 0.25,
            concessionFee: 0.0,
            stateSurcharge: 3.5999999,
            collectedDate: '2025-01-01 17:35:54.798+00',
            code: '1-1',
            label: '2025-01-03-Rental',
            collectionAllowed: true,
            isRentalChargesRefund: false
        },
        {
            isCardChange: false,
            id: 22180,
            chargeAmount: 30.0,
            chargeTax: 2.79262495,
            chargeTotal: 33.8499985,
            collectionDeadLine: '2025-01-01 04:00:00+00',
            rentalDate: '2025-01-04 04:00:00+00',
            collectionStatusId: 2,
            isDebt: true,
            toBeConsidered: true,
            isDiscount: false,
            createdDate: '2025-01-01 13:33:10.953271+00',
            chargesId: 'ch_3QcVplAHBUVqiOLM2UyQ4S6n',
            bookingId: 2259,
            userId: 1429,
            hostId: 1418,
            total: 36.6426239,
            registrationRecoveryFee: 0.25,
            concessionFee: 0.0,
            stateSurcharge: 3.5999999,
            collectedDate: '2025-01-01 17:35:54.798+00',
            code: '1-1',
            label: '2025-01-04-Rental',
            collectionAllowed: true,
            isRentalChargesRefund: false
        },
        {
            isCardChange: false,
            id: 22181,
            chargeAmount: 0.0,
            chargeTax: 0.0,
            chargeTotal: 0.0,
            collectionDeadLine: '2025-01-01 04:00:00+00',
            rentalDate: '2025-01-03 04:00:00+00',
            collectionStatusId: 2,
            isDebt: false,
            toBeConsidered: true,
            isDiscount: true,
            createdDate: '2025-01-01 13:33:10.953271+00',
            chargesId: 'ch_3QcVplAHBUVqiOLM2UyQ4S6n',
            bookingId: 2259,
            userId: 1429,
            hostId: 1418,
            total: 0.0,
            registrationRecoveryFee: 0.0,
            concessionFee: 0.0,
            stateSurcharge: 0.0,
            collectedDate: '2025-01-01 17:35:54.798+00',
            code: '1-1',
            label: '2025-01-03-Discount',
            collectionAllowed: true,
            isRentalChargesRefund: false
        }
    ],
    vehicleMessageContentResponse: [],
    vehicleConfigurationStatusList: [],
    notificationsQueues: [],
    changeCardResponses: [],
    userManagementServiceHealthChecks: [],
    tripChargesHealthChecks: [],
    bookingServiceHealthChecks: [],
    vehicleServiceHealthChecks: [],
    schedulerLogs: [],
    vehicleDetails: null,
    chargesIds: [],
    errorCode: '0',
    errorMessage: 'Data Retrived Successfully',
    cancellationDays: 0,
    codes: [
        {
            code: 0,
            key: 'SUCCESS',
            message: 'SUCCESS'
        }
    ]
};
