export const activeTrip = {
    driverHostConfigs: [],
    paymentIntent: null,
    driverReadinesses: [],
    depositHoldRespons: [],
    notificationEvents: [],
    tripConstraints: [],
    checkLists: [],
    paymentLogs: [],
    insuranceDetails: [],
    processedPayments: {},
    failedPaymentLogs: {},
    chargesList: null,
    pendingPayments: {},
    refundedAmount: 0.0,
    pendingDeductions: null,
    pendingRecords: {},
    hostBusinessConstraints: [],
    telematicsMessageLogs: [],
    turoMailRecords: [],
    hostPriceResponses: [],
    failedReservations: [],
    deliveryLocations: [],
    stripePayments: [],
    inAppNotifications: [],
    vehicleUnavaliblityDetails: [],
    vehicleLogResponses: [],
    reservationResponse: [],
    reserverList: [],
    userResponse: null,
    swapLogs: [],
    swapDetails: [],
    errorResponses: [],
    swapDetailResponses: [],
    vehicleHostDetails: null,
    paymentresponse: [],
    activetripresponse: [
        {
            cardDetails: [],
            deliveryLocations: null,
            isDebitCard: false,
            tripModificationHistories: [
                {
                    id: 848,
                    tripId: 1848,
                    modificationId: 1017,
                    initialStartTime: '2024-12-28 16:00:00+00',
                    initialEndTime: '2025-01-01 18:30:00+00',
                    updatedStartTime: '2024-12-28 18:30:00+00',
                    updatedEndTime: '2025-01-01 18:30:00+00',
                    initialTripAmount: 0.0,
                    updatedTripAmount: 0.0,
                    initialNumberOfDays: 0.0,
                    updatedNumberOfDays: 0.0,
                    initialTaxAmount: 0.0,
                    initialTripTaxAmount: 0.0,
                    updatedTaxAmount: 0.0,
                    updatedTripTaxAmount: 0.0,
                    modificationType: 'TRMODRED',
                    createdTime: '2024-12-28 07:24:15.119414+00',
                    initialDiscountPercentage: 0.0,
                    updatedDiscountPercentage: 0.0,
                    initialDiscountAmount: 0.0,
                    updatedDiscountAmount: 0.0,
                    initialTripDiscountedAmount: 0.0,
                    updatedTripDiscountedAmount: 0.0,
                    initialUpcharges: 0.0,
                    updatedUpcharges: 0.0,
                    initialDeliveryCost: 0.0,
                    updatedDeliveryCost: 0.0,
                    initialTripFee: 0.0,
                    updatedTripFee: 0.0,
                    initialCharges: 0.0,
                    updatedCharges: 0.0,
                    initialTaxPercentage: 0.0,
                    updatedTaxPercentage: 0.0,
                    initialNumberOfDaysDiscount: 0.0,
                    updatedNumberOfDaysDiscount: 0.0,
                    intialExtraMilageCost: 0.0,
                    updatedExtraMilageCost: 0.0,
                    initialconcessionCalculated: 0.0,
                    updatedconcessionCalculated: 0.0,
                    initialconcessionPercentage: 0.0,
                    updatedConcessionPercentage: 0.0,
                    initialConcessionFee: 0.0,
                    updatedConcessionFee: 0.0,
                    initialRegistrationRecoveryFee: 0.0,
                    updatedRegistrationRecoveryFee: 0.0,
                    initialStatesurchargetax: 0.0,
                    updatedStatesurchargetax: 0.0,
                    initialStatesurchargeamount: 0.0,
                    updatedStatesurchargeamount: 0.0,
                    initialTripFeeAmount: 0.0,
                    updatedTripFeeAmount: 0.0
                },
                {
                    id: 860,
                    tripId: 1848,
                    modificationId: 1032,
                    initialStartTime: '2024-12-28 18:30:00+00',
                    initialEndTime: '2025-01-01 18:30:00+00',
                    updatedStartTime: '2024-12-28 18:30:00+00',
                    updatedEndTime: '2024-12-31 18:30:00+00',
                    initialTripAmount: 0.0,
                    updatedTripAmount: 0.0,
                    initialNumberOfDays: 0.0,
                    updatedNumberOfDays: 0.0,
                    initialTaxAmount: 0.0,
                    initialTripTaxAmount: 0.0,
                    updatedTaxAmount: 0.0,
                    updatedTripTaxAmount: 0.0,
                    modificationType: 'TRMODRED',
                    createdTime: '2024-12-31 17:50:10.90301+00',
                    initialDiscountPercentage: 0.0,
                    updatedDiscountPercentage: 0.0,
                    initialDiscountAmount: 0.0,
                    updatedDiscountAmount: 0.0,
                    initialTripDiscountedAmount: 0.0,
                    updatedTripDiscountedAmount: 0.0,
                    initialUpcharges: 0.0,
                    updatedUpcharges: 0.0,
                    initialDeliveryCost: 0.0,
                    updatedDeliveryCost: 0.0,
                    initialTripFee: 0.0,
                    updatedTripFee: 0.0,
                    initialCharges: 0.0,
                    updatedCharges: 0.0,
                    initialTaxPercentage: 0.0,
                    updatedTaxPercentage: 0.0,
                    initialNumberOfDaysDiscount: 0.0,
                    updatedNumberOfDaysDiscount: 0.0,
                    intialExtraMilageCost: 0.0,
                    updatedExtraMilageCost: 0.0,
                    initialconcessionCalculated: 0.0,
                    updatedconcessionCalculated: 0.0,
                    initialconcessionPercentage: 0.0,
                    updatedConcessionPercentage: 0.0,
                    initialConcessionFee: 0.0,
                    updatedConcessionFee: 0.0,
                    initialRegistrationRecoveryFee: 0.0,
                    updatedRegistrationRecoveryFee: 0.0,
                    initialStatesurchargetax: 0.0,
                    updatedStatesurchargetax: 0.0,
                    initialStatesurchargeamount: 0.0,
                    updatedStatesurchargeamount: 0.0,
                    initialTripFeeAmount: 0.0,
                    updatedTripFeeAmount: 0.0
                }
            ],
            swapDetails: [],
            insuranceDetails: [],
            driverProfiles: [],
            vehicleImages: [
                {
                    idimage: 803,
                    orderNumber: 1,
                    isPrimary: false,
                    vehicleid: 271,
                    imagename:
                        'https://bundeestorage.blob.core.windows.net/bundeeprodstorage/1474%2F271%2F0d16e8907b6f42dc9b4dde03a97b6c00.jpg',
                    userid: 1474,
                    isactive: true,
                    createdate: '2024-08-16 00:27:13.786592+00',
                    updatedate: '2024-08-16 00:29:19.442+00',
                    imageUuid: '806'
                },
                {
                    idimage: 805,
                    orderNumber: 3,
                    isPrimary: false,
                    vehicleid: 271,
                    imagename:
                        'https://bundeestorage.blob.core.windows.net/bundeeprodstorage/1474%2F271%2F92f55e5cef4e43239febb97fdc33002a.jpg',
                    userid: 1474,
                    isactive: true,
                    createdate: '2024-08-16 00:27:14.177234+00',
                    updatedate: '2024-08-16 00:29:19.442+00',
                    imageUuid: '805'
                },
                {
                    idimage: 806,
                    orderNumber: 4,
                    isPrimary: false,
                    vehicleid: 271,
                    imagename:
                        'https://bundeestorage.blob.core.windows.net/bundeeprodstorage/1474%2F271%2F069770bb478849439eee6f740755f7be.jpg',
                    userid: 1474,
                    isactive: true,
                    createdate: '2024-08-16 00:27:14.627464+00',
                    updatedate: '2024-08-16 00:29:19.442+00',
                    imageUuid: '813'
                },
                {
                    idimage: 807,
                    orderNumber: 5,
                    isPrimary: false,
                    vehicleid: 271,
                    imagename:
                        'https://bundeestorage.blob.core.windows.net/bundeeprodstorage/1474%2F271%2F89317a7f1ce64fcf8adb4b4e733bb116.jpg',
                    userid: 1474,
                    isactive: true,
                    createdate: '2024-08-16 00:27:14.808655+00',
                    updatedate: '2024-08-16 00:29:19.442+00',
                    imageUuid: '814'
                },
                {
                    idimage: 808,
                    orderNumber: 6,
                    isPrimary: false,
                    vehicleid: 271,
                    imagename:
                        'https://bundeestorage.blob.core.windows.net/bundeeprodstorage/1474%2F271%2F9d803e01277d4842a19c7e1c9b0dcf75.jpg',
                    userid: 1474,
                    isactive: true,
                    createdate: '2024-08-16 00:27:14.988997+00',
                    updatedate: '2024-08-16 00:29:19.442+00',
                    imageUuid: '807'
                },
                {
                    idimage: 809,
                    orderNumber: 7,
                    isPrimary: false,
                    vehicleid: 271,
                    imagename:
                        'https://bundeestorage.blob.core.windows.net/bundeeprodstorage/1474%2F271%2F12a47f4356254df0be97bbf3ec542036.jpg',
                    userid: 1474,
                    isactive: true,
                    createdate: '2024-08-16 00:27:15.176366+00',
                    updatedate: '2024-08-16 00:29:19.442+00',
                    imageUuid: '808'
                },
                {
                    idimage: 810,
                    orderNumber: 8,
                    isPrimary: false,
                    vehicleid: 271,
                    imagename:
                        'https://bundeestorage.blob.core.windows.net/bundeeprodstorage/1474%2F271%2Febcd7e9ffd9d40e3ace151fc69c744c2.jpg',
                    userid: 1474,
                    isactive: true,
                    createdate: '2024-08-16 00:27:15.362062+00',
                    updatedate: '2024-08-16 00:29:19.442+00',
                    imageUuid: '809'
                },
                {
                    idimage: 804,
                    orderNumber: 2,
                    isPrimary: true,
                    vehicleid: 271,
                    imagename:
                        'https://bundeestorage.blob.core.windows.net/bundeeprodstorage/1474%2F271%2Fd4a810d17a1447c3952477fd8c9e95cb.jpg',
                    userid: 1474,
                    isactive: true,
                    createdate: '2024-08-16 00:27:13.942597+00',
                    updatedate: '2024-08-16 00:29:19.442+00',
                    imageUuid: '803'
                },
                {
                    idimage: 811,
                    orderNumber: 9,
                    isPrimary: false,
                    vehicleid: 271,
                    imagename:
                        'https://bundeestorage.blob.core.windows.net/bundeeprodstorage/1474%2F271%2F12e5690f597d42de846e82cfed67c580.jpg',
                    userid: 1474,
                    isactive: true,
                    createdate: '2024-08-16 00:27:15.57549+00',
                    updatedate: '2024-08-16 00:29:19.442+00',
                    imageUuid: '810'
                },
                {
                    idimage: 812,
                    orderNumber: 10,
                    isPrimary: false,
                    vehicleid: 271,
                    imagename:
                        'https://bundeestorage.blob.core.windows.net/bundeeprodstorage/1474%2F271%2Ff1b60f4777474ca7a90b83fde528d68e.jpg',
                    userid: 1474,
                    isactive: true,
                    createdate: '2024-08-16 00:27:15.749914+00',
                    updatedate: '2024-08-16 00:29:19.442+00',
                    imageUuid: '811'
                },
                {
                    idimage: 813,
                    orderNumber: 11,
                    isPrimary: false,
                    vehicleid: 271,
                    imagename:
                        'https://bundeestorage.blob.core.windows.net/bundeeprodstorage/1474%2F271%2F85445a789de44553a343e98703f20c0a.jpg',
                    userid: 1474,
                    isactive: true,
                    createdate: '2024-08-16 00:27:16.203539+00',
                    updatedate: '2024-08-16 00:29:19.442+00',
                    imageUuid: '812'
                },
                {
                    idimage: 814,
                    orderNumber: 12,
                    isPrimary: false,
                    vehicleid: 271,
                    imagename:
                        'https://bundeestorage.blob.core.windows.net/bundeeprodstorage/1474%2F271%2Fc6fe86e35d144f639ac2f46de8f3429e.jpg',
                    userid: 1474,
                    isactive: true,
                    createdate: '2024-08-16 00:27:16.438558+00',
                    updatedate: '2024-08-16 00:29:19.442+00',
                    imageUuid: '804'
                }
            ],
            tripPaymentTokens: [
                {
                    capturedDays: 0,
                    depositHoldAmount: 0.0,
                    chargedAmountOnHold: 0.0,
                    id: 1915,
                    reservationid: 1881,
                    userid: 1472,
                    hostid: 1474,
                    channelid: 4,
                    vehicleid: 271,
                    deductionfrequencyconfigid: 0,
                    paymentauthorizationconfigid: 0,
                    authorizationamount: 0.0,
                    authorizationpercentage: 0.0,
                    releasedAmountOnHold: 0.0,
                    totaldays: 0.0,
                    perdayamount: 0.0,
                    totalamount: 0.0,
                    createddate: '2024-12-28 06:35:10.571929+00',
                    updateddate: null,
                    tripid: 1848,
                    strippaymenttoken: null,
                    strippaymentid: null,
                    strippaymenttokenactiveflag: false,
                    isactive: true,
                    paymentrecieveddate: '2024-12-28 06:35:10.571929+00',
                    stripetransactiondetails: null,
                    paymentmethodidtoken: null,
                    customertoken: null,
                    setupIntentToken: null,
                    tripAmount: 0.0,
                    taxAmount: 0.0,
                    tripTaxAmount: 0.0,
                    discountedDays: 0.0,
                    discountPercentage: 0.0,
                    discountAmount: 0.0,
                    tripDiscountedAmount: 0.0,
                    upCharges: 0.0,
                    deliveryCost: 0.0,
                    tripFee: 0.0,
                    charges: 0.0,
                    taxPercentage: 0.0,
                    numberOfDaysDiscount: 0.0,
                    concessionCalculated: 0.0,
                    concessionPercentage: 0.0,
                    concessionFee: 0.0,
                    registrationRecoveryFee: 0.0,
                    extreaMilageCost: 0.0,
                    Statesurchargetax: 0.0,
                    Statesurchargeamount: 0.0,
                    tripFeeAmount: 0.0,
                    capturedAmount: 0.0,
                    refundAmount: 0.0,
                    extraMileageCost: 0.0,
                    extraMilage: 0.0,
                    lateFee: 0.0,
                    extraDayCharges: 0.0,
                    registrationFee: 0.0,
                    averageRentalDays: 0.0
                }
            ],
            paymentTransactions: [],
            successfullPaymentTransactions: [],
            cancelresponse: [],
            tripSlipPayments: [],
            rentalCharges: [],
            tripChargeLedgers: [],
            paymentCaptures: [],
            tripPayementAuthResponses: [],
            vehicleDetails: [
                {
                    id: 271,
                    vin: '1G1FW6S01H4184399',
                    make: 'CHEVROLET',
                    model: 'Bolt EV',
                    desciption:
                        'Save money on gas, go electric!  Enjoy the fun-to-drive ALL ELECTRIC Chevy Bolt EV.  The Bolt EV is a suprisingly roomy hatchback - completely normal adults can sit in the back seat.\n\nAll the room and range of a Tesla with none of the extra baggage.  The Bolt even comes with a completely normal license plate that does not say “look at me”. \n\nThe Bolt EV offers an EPA estimated range of 240 miles, less if you drive like a crazy person. The Bolt EV is not DC Fast capable, so you can’t use the fastest DC Fast chargers.  You get free L2 charging at *most* chargers.\n\nAll-Electric 2017 Chevy Bolt EV features: \n\n✅ Keyless ignition\n✅ Apple CarPlay / Android Whatever\n✅ Bluetooth\n✅ Tilt and telescopic steering wheel\n✅ Audio and cruise controls on steering wheel\n✅ Electric power steering\n✅ Rear parking sensors\n✅ Cruise control\n✅ Backup Camera\n✅ Front and rear cupholders',
                    year: '2017',
                    cityname: 'Austin',
                    price_per_hr: 39,
                    latitude: '30.27636',
                    longitude: '-97.7294',
                    address1: '900 East 16th Street',
                    address2: '',
                    zipcode: '78702',
                    state: 'Texas',
                    name: 'Electric',
                    bedtype: null,
                    bodyclass: null,
                    busfloortype: null,
                    bustype: null,
                    cabtype: null,
                    custommotortype: null,
                    doors: '4',
                    drivetype: null,
                    wlectrificationlevel: null,
                    enginebrake: null,
                    enginepower: null,
                    frontairbaglocation: null,
                    fueltypeprimary: null,
                    manufacturename: null,
                    motorcyclechasistype: null,
                    motorcyclesuspensiontype: null,
                    othetengineinfo: null,
                    OtherRestraintSystemInfo: null,
                    plantCity: null,
                    plantCompanyName: null,
                    plantCountry: null,
                    plantstate: null,
                    seatbelttype: null,
                    SideAirBagLocations: null,
                    SteeringLocation: null,
                    tirePressure: null,
                    trailerBodyType: null,
                    trailerTypeConnection: null,
                    trim: null,
                    turbo: null,
                    vehicleType: null,
                    count: 0,
                    tripcount: 16,
                    rating: 2.0,
                    wishList: false,
                    vehicleDescription: null,
                    seatingCapacity: '5',
                    insuranceHeader: null,
                    insuranceHeaderType: null,
                    insuranceDetails1: null,
                    insuranceDetails2: null,
                    insuranceDetails3: null,
                    parkingDetails: null,
                    guideLines: null,
                    policies: null,
                    imageresponse: [
                        {
                            idimage: 803,
                            orderNumber: 1,
                            isPrimary: false,
                            vehicleid: 271,
                            imagename:
                                'https://bundeestorage.blob.core.windows.net/bundeeprodstorage/1474%2F271%2F0d16e8907b6f42dc9b4dde03a97b6c00.jpg',
                            userid: 1474,
                            isactive: true,
                            createdate: '2024-08-16 00:27:13.786592+00',
                            updatedate: '2024-08-16 00:29:19.442+00',
                            imageUuid: '806'
                        },
                        {
                            idimage: 805,
                            orderNumber: 3,
                            isPrimary: false,
                            vehicleid: 271,
                            imagename:
                                'https://bundeestorage.blob.core.windows.net/bundeeprodstorage/1474%2F271%2F92f55e5cef4e43239febb97fdc33002a.jpg',
                            userid: 1474,
                            isactive: true,
                            createdate: '2024-08-16 00:27:14.177234+00',
                            updatedate: '2024-08-16 00:29:19.442+00',
                            imageUuid: '805'
                        },
                        {
                            idimage: 806,
                            orderNumber: 4,
                            isPrimary: false,
                            vehicleid: 271,
                            imagename:
                                'https://bundeestorage.blob.core.windows.net/bundeeprodstorage/1474%2F271%2F069770bb478849439eee6f740755f7be.jpg',
                            userid: 1474,
                            isactive: true,
                            createdate: '2024-08-16 00:27:14.627464+00',
                            updatedate: '2024-08-16 00:29:19.442+00',
                            imageUuid: '813'
                        },
                        {
                            idimage: 807,
                            orderNumber: 5,
                            isPrimary: false,
                            vehicleid: 271,
                            imagename:
                                'https://bundeestorage.blob.core.windows.net/bundeeprodstorage/1474%2F271%2F89317a7f1ce64fcf8adb4b4e733bb116.jpg',
                            userid: 1474,
                            isactive: true,
                            createdate: '2024-08-16 00:27:14.808655+00',
                            updatedate: '2024-08-16 00:29:19.442+00',
                            imageUuid: '814'
                        },
                        {
                            idimage: 808,
                            orderNumber: 6,
                            isPrimary: false,
                            vehicleid: 271,
                            imagename:
                                'https://bundeestorage.blob.core.windows.net/bundeeprodstorage/1474%2F271%2F9d803e01277d4842a19c7e1c9b0dcf75.jpg',
                            userid: 1474,
                            isactive: true,
                            createdate: '2024-08-16 00:27:14.988997+00',
                            updatedate: '2024-08-16 00:29:19.442+00',
                            imageUuid: '807'
                        },
                        {
                            idimage: 809,
                            orderNumber: 7,
                            isPrimary: false,
                            vehicleid: 271,
                            imagename:
                                'https://bundeestorage.blob.core.windows.net/bundeeprodstorage/1474%2F271%2F12a47f4356254df0be97bbf3ec542036.jpg',
                            userid: 1474,
                            isactive: true,
                            createdate: '2024-08-16 00:27:15.176366+00',
                            updatedate: '2024-08-16 00:29:19.442+00',
                            imageUuid: '808'
                        },
                        {
                            idimage: 810,
                            orderNumber: 8,
                            isPrimary: false,
                            vehicleid: 271,
                            imagename:
                                'https://bundeestorage.blob.core.windows.net/bundeeprodstorage/1474%2F271%2Febcd7e9ffd9d40e3ace151fc69c744c2.jpg',
                            userid: 1474,
                            isactive: true,
                            createdate: '2024-08-16 00:27:15.362062+00',
                            updatedate: '2024-08-16 00:29:19.442+00',
                            imageUuid: '809'
                        },
                        {
                            idimage: 804,
                            orderNumber: 2,
                            isPrimary: true,
                            vehicleid: 271,
                            imagename:
                                'https://bundeestorage.blob.core.windows.net/bundeeprodstorage/1474%2F271%2Fd4a810d17a1447c3952477fd8c9e95cb.jpg',
                            userid: 1474,
                            isactive: true,
                            createdate: '2024-08-16 00:27:13.942597+00',
                            updatedate: '2024-08-16 00:29:19.442+00',
                            imageUuid: '803'
                        },
                        {
                            idimage: 811,
                            orderNumber: 9,
                            isPrimary: false,
                            vehicleid: 271,
                            imagename:
                                'https://bundeestorage.blob.core.windows.net/bundeeprodstorage/1474%2F271%2F12e5690f597d42de846e82cfed67c580.jpg',
                            userid: 1474,
                            isactive: true,
                            createdate: '2024-08-16 00:27:15.57549+00',
                            updatedate: '2024-08-16 00:29:19.442+00',
                            imageUuid: '810'
                        },
                        {
                            idimage: 812,
                            orderNumber: 10,
                            isPrimary: false,
                            vehicleid: 271,
                            imagename:
                                'https://bundeestorage.blob.core.windows.net/bundeeprodstorage/1474%2F271%2Ff1b60f4777474ca7a90b83fde528d68e.jpg',
                            userid: 1474,
                            isactive: true,
                            createdate: '2024-08-16 00:27:15.749914+00',
                            updatedate: '2024-08-16 00:29:19.442+00',
                            imageUuid: '811'
                        },
                        {
                            idimage: 813,
                            orderNumber: 11,
                            isPrimary: false,
                            vehicleid: 271,
                            imagename:
                                'https://bundeestorage.blob.core.windows.net/bundeeprodstorage/1474%2F271%2F85445a789de44553a343e98703f20c0a.jpg',
                            userid: 1474,
                            isactive: true,
                            createdate: '2024-08-16 00:27:16.203539+00',
                            updatedate: '2024-08-16 00:29:19.442+00',
                            imageUuid: '812'
                        },
                        {
                            idimage: 814,
                            orderNumber: 12,
                            isPrimary: false,
                            vehicleid: 271,
                            imagename:
                                'https://bundeestorage.blob.core.windows.net/bundeeprodstorage/1474%2F271%2Fc6fe86e35d144f639ac2f46de8f3429e.jpg',
                            userid: 1474,
                            isactive: true,
                            createdate: '2024-08-16 00:27:16.438558+00',
                            updatedate: '2024-08-16 00:29:19.442+00',
                            imageUuid: '804'
                        }
                    ],
                    tripreview: [
                        {
                            reviewid: 2,
                            reservationid: 1219,
                            vehicleid: 271,
                            userid: 1556,
                            rating: 2,
                            tripid: 1219,
                            avg: 0.0,
                            comments: 'lots of improvement needs to be made with their UI customer service spot on',
                            createddate: '2024-09-24 04:38:52.357998+00',
                            updateddate: '2024-09-24 04:38:52.357998+00',
                            isactive: true,
                            hostId: 0
                        }
                    ]
                }
            ],
            tripModificationDetails: [
                {
                    id: 1032,
                    tripId: 1848,
                    reservationId: 1881,
                    userId: 1472,
                    vehicleID: 271,
                    tripPaymentTokenID: 1915,
                    hostID: 1474,
                    channelID: 4,
                    modificationTypeCode: 'TRMODRED',
                    modificationTypeCodeID: 2,
                    totalDays: 0.0,
                    amountPerDays: 0.0,
                    tripAmount: 0.0,
                    paymentAuthPercentage: 0.0,
                    authAmount: 0.0,
                    totalAmount: 0.0,
                    tripAuthConfigID: 0,
                    tripStatusID: 14,
                    tripStatusCode: 'REQMODAPP',
                    isActive: true,
                    createdDate: '2024-12-31 17:50:10.897665+00',
                    updatedDate: null,
                    startTime: '2024-12-28 18:30:00+00',
                    endTime: '2024-12-31 18:30:00+00',
                    taxAmount: 0.0,
                    tripTaxAmount: 0.0,
                    comments: null,
                    pickupTime: null,
                    dropTime: null,
                    modificationStatus: 'Modification Approved',
                    colorCode: null,
                    discountPercentage: 0.0,
                    discountAmount: 0.0,
                    tripDiscountedAmount: 0.0,
                    upCharges: 0.0,
                    deliveryCost: 0.0,
                    tripFee: 0.0,
                    charges: 0.0,
                    taxPercentage: 0.0,
                    numberOfDaysDiscount: 0.0,
                    concessionCalculated: 0.0,
                    concessionPercentage: 0.0,
                    concessionFee: 0.0,
                    registrationRecoveryFee: 0.0,
                    extraMilageCost: 0.0,
                    Statesurchargetax: 0.0,
                    Statesurchargeamount: 0.0,
                    tripFeeAmount: 0.0
                },
                {
                    id: 1017,
                    tripId: 1848,
                    reservationId: 1881,
                    userId: 1472,
                    vehicleID: 271,
                    tripPaymentTokenID: 1915,
                    hostID: 1474,
                    channelID: 4,
                    modificationTypeCode: 'TRMODRED',
                    modificationTypeCodeID: 2,
                    totalDays: 0.0,
                    amountPerDays: 0.0,
                    tripAmount: 0.0,
                    paymentAuthPercentage: 0.0,
                    authAmount: 0.0,
                    totalAmount: 0.0,
                    tripAuthConfigID: 0,
                    tripStatusID: 14,
                    tripStatusCode: 'REQMODAPP',
                    isActive: true,
                    createdDate: '2024-12-28 07:24:15.114184+00',
                    updatedDate: null,
                    startTime: '2024-12-28 18:30:00+00',
                    endTime: '2025-01-01 18:30:00+00',
                    taxAmount: 0.0,
                    tripTaxAmount: 0.0,
                    comments: null,
                    pickupTime: null,
                    dropTime: null,
                    modificationStatus: 'Modification Approved',
                    colorCode: null,
                    discountPercentage: 0.0,
                    discountAmount: 0.0,
                    tripDiscountedAmount: 0.0,
                    upCharges: 0.0,
                    deliveryCost: 0.0,
                    tripFee: 0.0,
                    charges: 0.0,
                    taxPercentage: 0.0,
                    numberOfDaysDiscount: 0.0,
                    concessionCalculated: 0.0,
                    concessionPercentage: 0.0,
                    concessionFee: 0.0,
                    registrationRecoveryFee: 0.0,
                    extraMilageCost: 0.0,
                    Statesurchargetax: 0.0,
                    Statesurchargeamount: 0.0,
                    tripFeeAmount: 0.0
                }
            ],
            tripStatusTransactionResponses: [
                {
                    id: 118391,
                    tripid: 1848,
                    reservationid: 1881,
                    userid: 1472,
                    vehicleid: 271,
                    hostid: 1474,
                    channelid: 4,
                    fromstatus: 'REAPP',
                    tostatus: 'REQMODAPP',
                    changedby: null,
                    isactive: true,
                    createddate: '2024-12-28 07:24:18.266171+00',
                    updatedate: null,
                    comments: 'The trip was Reduced.',
                    createdBy: null,
                    viewed: false,
                    rentalAgrrementStatus: null,
                    isRentalStatus: false,
                    modificationId: 1017,
                    metaData: null,
                    isEventmessageConfigured: false,
                    eventMessage: null
                },
                {
                    id: 118511,
                    tripid: 1848,
                    reservationid: 1881,
                    userid: 1472,
                    vehicleid: 271,
                    hostid: 1474,
                    channelid: 4,
                    fromstatus: 'REAPP',
                    tostatus: 'REQMODAPP',
                    changedby: null,
                    isactive: true,
                    createddate: '2024-12-31 17:50:13.537704+00',
                    updatedate: null,
                    comments: 'The trip was Reduced.',
                    createdBy: null,
                    viewed: false,
                    rentalAgrrementStatus: null,
                    isRentalStatus: false,
                    modificationId: 1032,
                    metaData: null,
                    isEventmessageConfigured: false,
                    eventMessage: null
                },
                {
                    id: 118388,
                    tripid: 1848,
                    reservationid: 1881,
                    userid: 1472,
                    vehicleid: 271,
                    hostid: 1474,
                    channelid: 4,
                    fromstatus: 'No booking',
                    tostatus: 'REREQ',
                    changedby: 'USER',
                    isactive: true,
                    createddate: '2024-12-28 06:35:10.583298+00',
                    updatedate: null,
                    comments: 'Reservation was created',
                    createdBy: null,
                    viewed: false,
                    rentalAgrrementStatus: '',
                    isRentalStatus: false,
                    modificationId: 0,
                    metaData: null,
                    isEventmessageConfigured: false,
                    eventMessage: null
                },
                {
                    id: 118390,
                    tripid: 1848,
                    reservationid: 1881,
                    userid: 1472,
                    vehicleid: 271,
                    hostid: 1474,
                    channelid: 4,
                    fromstatus: 'REREQ',
                    tostatus: 'REAPP',
                    changedby: 'HOST',
                    isactive: true,
                    createddate: '2024-12-28 06:35:16.83616+00',
                    updatedate: null,
                    comments: 'The trip has been Approved.',
                    createdBy: null,
                    viewed: false,
                    rentalAgrrementStatus: '',
                    isRentalStatus: false,
                    modificationId: 0,
                    metaData: null,
                    isEventmessageConfigured: false,
                    eventMessage: null
                }
            ],
            transactionCheckLists: [],
            tripConstraints: [
                {
                    id: 1686,
                    upcharges: 0,
                    mileageconstraint: 525,
                    minmaxdays: 526,
                    discounts: 566,
                    deliverydetails: 0,
                    guestinstructionandguidelines: 0,
                    tripId: 1848,
                    vehicleId: 271,
                    isActive: true,
                    amountCaptured: 0.0,
                    extraCharges: 0.0,
                    tripAmount: 0.0,
                    extraMileageCost: 0.0,
                    extraMilage: 0.0
                }
            ],
            hostTripStartingBlobs: [],
            hostTripCompletingBlobs: [],
            driverTripStartingBlobs: [],
            driverTripCompletingBlobs: [],
            cancellationRequestedMessage: null,
            cancellationRequested: false,
            depositToBeCollected: true,
            depositToBeCollectedForTrip: false,
            depositRenewFailed: false,
            debitHoldReleased: false,
            closingMilesEntered: false,
            extraChargesEntered: false,
            isCardExtensionFailed: false,
            cardExtensionFailedReason: null,
            failedtripextensionmessage: null,
            failedautotripExtension: false,
            userImage: null,
            completedDate: null,
            userEmail: null,
            userMobilePhone: 'tel:+19253146621',
            invoiceUrl: null,
            rentalAgrrementUrl: null,
            paymentFailedReason: null,
            paymentFailed: false,
            is24HoursBooking: true,
            tripid: 1848,
            statusCode: 'REAPP',
            reservationid: 1881,
            actualstarttime: null,
            actualendttime: null,
            tripstatus: 2,
            openingMiles: 0.0,
            closingMiles: 0.0,
            userid: 1472,
            vehicleId: 271,
            channelId: 4,
            isactive: true,
            newRequest: false,
            startFailed: false,
            failedDriverVerifications: false,
            newRequestMessage: null,
            startFailedMessage: null,
            failedDriverVerificationsMessage: null,
            createddate: '2024-12-28 06:35:10.567634+00',
            updateddate: '2024-12-31 17:50:10.91+00',
            hostid: 1474,
            starttime: '2024-12-28 18:30:00+00',
            endtime: '2024-12-31 18:30:00+00',
            status: 'Approved',
            tripCount: '970',
            pickupLocation: 'NA',
            logCompleted: 'false',
            unreadMsgCount: '0',
            vehmake: 'CHEVROLET',
            vehmodel: 'Bolt EV',
            vehyear: '2017',
            vehcityname: ' Austin',
            vehzipcode: '78702',
            vehaddress1: '900 East 16th Street',
            vehaddress2: '',
            vehstate: 'Texas',
            userFirstName: 'Sudhin Domala',
            userlastName: null,
            cancellationDays: 2,
            bookingId: 'BUN20241200ce5dd073-3715-452c-b8d8-3e381e22ecc2',
            message: null,
            colorCode: '#34A853',
            channelName: 'turo',
            delivery: false,
            airportDelivery: false,
            isRentalAgreed: false,
            rentalAgreedDate: null,
            vehicleNumber: 'VBP3885',
            hostFirstName: ' ',
            hostLastName: 'Flux Electrics',
            hostPhoneNumber: '+17375203589',
            hostImage: 'https://bundeestorage.blob.core.windows.net/bundeeprodstorage/%2F1474%2Ff8de776e463047c9ac680fa39bbd230f.jpg',
            isLicenseVerified: false,
            drivingLicenseStatus: null,
            isInsuranceVerified: false,
            insuranceStatus: null,
            isPhoneVarified: false
        }
    ],
    cancellationRequestedTrips: [],
    failedToStartTrips: [],
    failedTripExtensions: [],
    failedCardExtensions: null,
    failedPayments: [],
    newRequests: [],
    failedDriverVerifications: [],
    locationResponses: [],
    activeTrips: [],
    userResponses: null,
    vehicles: null,
    paymentTransactions: [],
    tripreview: [],
    tripresponse: [],
    imageresponse: [],
    channels: [],
    tripPaymentTokens: [],
    reservationresponse: null,
    deductionFrequencyConfigs: [],
    pdfResponses: [],
    count: 0,
    deductionFrequencyDays: null,
    paymentRequests: [],
    deductionEventConfig: [],
    deductionDetails: [],
    paymentAuthorizationCategories: [],
    tripPaymentCategories: [],
    paymentAuthConfigs: [],
    paymentCaptures: [],
    capturedPaymentToken: [],
    cancellationResponses: [],
    authorisationPerResponses: [],
    tripModificationTypes: [],
    tripModificationDetails: [],
    trippaymentcategorymappingResponses: [],
    tripModificationResponses: [],
    tripSlipPayments: [],
    paymentInvoices: [],
    hostInsights: [],
    vehicleAllDetails: [],
    pushnotifications: [],
    statusTransactions: [],
    tripPayementAuthResponses: null,
    masterCheckListTypes: [],
    masterCheckLists: [],
    hostCheckListMappings: [],
    transactionCheckLists: [],
    hostRatingDetails: [],
    hostModificationResponses: [],
    paymentPendings: [],
    tripStatusTransactionResponses: null,
    channelRegistrations: [],
    userVehicleBookings: [],
    tripModificationHistories: [],
    tripPaymentHistoryList: [],
    priceCalculatedList: [],
    driverActivities: [],
    apiMapBoxMAppingResponses: [],
    driverProfiles: [],
    sendGRidRests: [],
    depositHoldConfigurations: [],
    sendGridResponses: [],
    locations: null,
    vehicleBusinessConstraints: [],
    tripMediaFilesResponses: [],
    hostTripStartingBlobs: [],
    hostTripCompletingBlobs: [],
    driverTripStartingBlobs: [],
    driverTripCompletingBlobs: [],
    messageNotifications: [],
    ids: [],
    failedIds: [],
    userTripDetails: [],
    autoExtensionResponses: [],
    failedTuroTripsList: [],
    driverUpcomingTripsResponses: [],
    driverTripDetails: [],
    driverUpComingTrips: [],
    driverTripsCounts: [],
    driverRentalAmounts: [],
    driverOnGoingTripResponse: [],
    chargeTypes: [],
    collectionStatusList: [
        {
            id: 1,
            statusName: 'Future'
        },
        {
            id: 3,
            statusName: 'Pending'
        },
        {
            id: 4,
            statusName: 'Failed'
        },
        {
            id: 2,
            statusName: 'Collected'
        },
        {
            id: 5,
            statusName: 'Refunded'
        },
        {
            id: 6,
            statusName: 'Deposit_hold'
        }
    ],
    tripChargeLedgerList: [],
    rentalCharges: [],
    vehicleMessageContentResponse: [],
    vehicleConfigurationStatusList: [],
    notificationsQueues: [],
    changeCardResponses: [],
    userManagementServiceHealthChecks: [],
    tripChargesHealthChecks: [],
    bookingServiceHealthChecks: [],
    vehicleServiceHealthChecks: [],
    schedulerLogs: [],
    vehicleDetails: null,
    errorCode: '0',
    errorMessage: 'Data Retrived Successfully',
    cancellationDays: 0,
    codes: [
        {
            code: 0,
            key: 'SUCCESS',
            message: 'SUCCESS'
        }
    ]
};
