import { createEnv } from '@t3-oss/env-nextjs';
import { z } from 'zod';

const serverEnv = createEnv({
    emptyStringAsUndefined: true,
    server: {
        AUTH_SECRET: z.string(),
        AUTH_URL: z.string(),
        AUTH_TRUST_HOST: z.string()
    },
    experimental__runtimeEnv: process.env
});

const clientEnv = createEnv({
    emptyStringAsUndefined: true,
    client: {
        NEXT_PUBLIC_APP_NODE_ENV: z.union([z.literal('development'), z.literal('test'), z.literal('production')]),
        NEXT_PUBLIC_USER_MANAGEMENT_BASEURL: z.string(),
        NEXT_PUBLIC_HOST_VEHICLE_SERVICES_BASEURL: z.string(),
        NEXT_PUBLIC_BOOKING_SERVICES_BASEURL: z.string(),
        NEXT_PUBLIC_AVAILABILITY_BASEURL: z.string(),
        NEXT_PUBLIC_USER_TOKEN_BASEURL: z.string(),
        NEXT_PUBLIC_CHAT_SERVICE_BASEURL: z.string(),
        NEXT_PUBLIC_TELEMATICS_SERVICE_BASEURL: z.string(),
        NEXT_PUBLIC_FALLBACK_BUNDEE_AUTH_TOKEN: z.string(),
        NEXT_PUBLIC_CHAT_SERVICE_PASSWORD: z.string(),
        NEXT_PUBLIC_FIREBASE_APIKEY: z.string(),
        NEXT_PUBLIC_FIREBASE_AUTHDOMAIN: z.string(),
        NEXT_PUBLIC_FIREBASE_PROJECTID: z.string(),
        NEXT_PUBLIC_FIREBASE_STORAGEBUCKET: z.string(),
        NEXT_PUBLIC_FIREBASE_MESSAGINGSENDERID: z.string(),
        NEXT_PUBLIC_FIREBASE_APPID: z.string(),
        NEXT_PUBLIC_MAPBOX_BASE_URL: z.string(),
        NEXT_PUBLIC_MAPBOX_SEARCH_LIMIT: z.string(),
        NEXT_PUBLIC_MAPBOX_SEARCH_COUNTRY: z.string(),
        NEXT_PUBLIC_MAPBOX_RESPONSE_LANGUAGE: z.string(),
        NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN: z.string(),
        NEXT_PUBLIC_IDSCAN_BEARER_TOKEN_BUNDEE: z.string(),
        NEXT_PUBLIC_IDSCAN_BEARER_TOKEN_FLUX: z.string()
    },
    experimental__runtimeEnv: {
        NEXT_PUBLIC_APP_NODE_ENV: process.env.NEXT_PUBLIC_APP_NODE_ENV,
        NEXT_PUBLIC_USER_MANAGEMENT_BASEURL: process.env.NEXT_PUBLIC_USER_MANAGEMENT_BASEURL,
        NEXT_PUBLIC_HOST_VEHICLE_SERVICES_BASEURL: process.env.NEXT_PUBLIC_HOST_VEHICLE_SERVICES_BASEURL,
        NEXT_PUBLIC_BOOKING_SERVICES_BASEURL: process.env.NEXT_PUBLIC_BOOKING_SERVICES_BASEURL,
        NEXT_PUBLIC_AVAILABILITY_BASEURL: process.env.NEXT_PUBLIC_AVAILABILITY_BASEURL,
        NEXT_PUBLIC_USER_TOKEN_BASEURL: process.env.NEXT_PUBLIC_USER_TOKEN_BASEURL,
        NEXT_PUBLIC_CHAT_SERVICE_BASEURL: process.env.NEXT_PUBLIC_CHAT_SERVICE_BASEURL,
        NEXT_PUBLIC_TELEMATICS_SERVICE_BASEURL: process.env.NEXT_PUBLIC_TELEMATICS_SERVICE_BASEURL,
        NEXT_PUBLIC_FALLBACK_BUNDEE_AUTH_TOKEN: process.env.NEXT_PUBLIC_FALLBACK_BUNDEE_AUTH_TOKEN,
        NEXT_PUBLIC_CHAT_SERVICE_PASSWORD: process.env.NEXT_PUBLIC_CHAT_SERVICE_PASSWORD,
        NEXT_PUBLIC_FIREBASE_APIKEY: process.env.NEXT_PUBLIC_FIREBASE_APIKEY,
        NEXT_PUBLIC_FIREBASE_AUTHDOMAIN: process.env.NEXT_PUBLIC_FIREBASE_AUTHDOMAIN,
        NEXT_PUBLIC_FIREBASE_PROJECTID: process.env.NEXT_PUBLIC_FIREBASE_PROJECTID,
        NEXT_PUBLIC_FIREBASE_STORAGEBUCKET: process.env.NEXT_PUBLIC_FIREBASE_STORAGEBUCKET,
        NEXT_PUBLIC_FIREBASE_MESSAGINGSENDERID: process.env.NEXT_PUBLIC_FIREBASE_MESSAGINGSENDERID,
        NEXT_PUBLIC_FIREBASE_APPID: process.env.NEXT_PUBLIC_FIREBASE_APPID,
        NEXT_PUBLIC_MAPBOX_BASE_URL: process.env.NEXT_PUBLIC_MAPBOX_BASE_URL,
        NEXT_PUBLIC_MAPBOX_SEARCH_LIMIT: process.env.NEXT_PUBLIC_MAPBOX_SEARCH_LIMIT,
        NEXT_PUBLIC_MAPBOX_SEARCH_COUNTRY: process.env.NEXT_PUBLIC_MAPBOX_SEARCH_COUNTRY,
        NEXT_PUBLIC_MAPBOX_RESPONSE_LANGUAGE: process.env.NEXT_PUBLIC_MAPBOX_RESPONSE_LANGUAGE,
        NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN: process.env.NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN,
        NEXT_PUBLIC_IDSCAN_BEARER_TOKEN_BUNDEE: process.env.NEXT_PUBLIC_IDSCAN_BEARER_TOKEN_BUNDEE,
        NEXT_PUBLIC_IDSCAN_BEARER_TOKEN_FLUX: process.env.NEXT_PUBLIC_IDSCAN_BEARER_TOKEN_FLUX
    }
});

export const env = {
    ...clientEnv,
    ...serverEnv,
    USER_MANAGEMENT_BASEURL: clientEnv.NEXT_PUBLIC_USER_MANAGEMENT_BASEURL,
    HOST_VEHICLE_SERVICES_BASEURL: clientEnv.NEXT_PUBLIC_HOST_VEHICLE_SERVICES_BASEURL,
    BOOKING_SERVICES_BASEURL: clientEnv.NEXT_PUBLIC_BOOKING_SERVICES_BASEURL,
    AVAILABILITY_BASEURL: clientEnv.NEXT_PUBLIC_AVAILABILITY_BASEURL,
    USER_TOKEN_BASEURL: clientEnv.NEXT_PUBLIC_USER_TOKEN_BASEURL,
    CHAT_SERVICE_BASEURL: clientEnv.NEXT_PUBLIC_CHAT_SERVICE_BASEURL,
    TELEMATICS_SERVICE_BASEURL: clientEnv.NEXT_PUBLIC_TELEMATICS_SERVICE_BASEURL
};
